import { PrismaClient } from "../src/generated/prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";

const connectionString =
  process.env.DATABASE_URL ||
  "postgres://96fa7b5f5df7497cfb8ce2a6d714677abffa491f1db8fd2e12ad176ad5ecc95c:sk_myDZlhG3DBQQ5amR4Lj8F@db.prisma.io:5432/postgres?sslmode=require";

const db = new PrismaClient({ adapter: new PrismaPg({ connectionString }) });

const rawData = [
  { name: "Hide and seek 10rs", cat: "Snacks", wp: 180, rp: 180, unit: "pc" },
  { name: "Dabur Honey 250gm", cat: "Kirana", wp: 112, rp: 118, unit: "pc" },
  { name: "Parle Toffees Jar", cat: "Snacks", wp: 130, rp: 130, unit: "jar" },
  { name: "Aloo Bhujia 5rs", cat: "Snacks", wp: 52, rp: 52, unit: "pc" },
  { name: "Ponds Lotion 120ml", cat: "Household", wp: 105, rp: 105, unit: "pc" },
  { name: "Glass 250ml", cat: "Stationery", wp: 18.75, rp: 25, unit: "pc" },
  { name: "Munakka 250gm", cat: "Masala", wp: 150, rp: 150, unit: "g" },
  { name: "Nycil Powder 150ml", cat: "Household", wp: 135, rp: 135, unit: "pc" },
  { name: "Parachute Bottle 100ml", cat: "Household", wp: 64, rp: 65, unit: "pc" },
  { name: "Matcha Chai 800g", cat: "Kirana", wp: 300, rp: 300, unit: "g" },
  { name: "Dettol Set", cat: "Household", wp: 280, rp: 280, unit: "set" },
  { name: "Gutir Rice 1kg", cat: "Rice & Atta", wp: 110, rp: 110, unit: "kg" },
  { name: "Boondi 10rs", cat: "Snacks", wp: 70, rp: 70, unit: "pc" },
  { name: "Rajshree 20rs", cat: "Snacks", wp: 260, rp: 260, unit: "pc" },
  { name: "Mirch Powder Special 1kg", cat: "Masala", wp: 350, rp: 370, unit: "kg" },
  { name: "Dew 2L", cat: "Drinks", wp: 75.56, rp: 75.56, unit: "pc" },
  { name: "Maida 500gm", cat: "Rice & Atta", wp: 28, rp: 30, unit: "pc" },
  { name: "Close Up 20rs", cat: "Kirana", wp: 17.5, rp: 18, unit: "pc" },
  { name: "Clinic Plus Shampoo 400ml", cat: "Household", wp: 280, rp: 280, unit: "pc" },
  { name: "Patanjali Oil 1L", cat: "Household", wp: 165, rp: 165, unit: "l" },
  { name: "Black Pen Ball", cat: "Stationery", wp: 20, rp: 20, unit: "pc" },
  { name: "Rajshree 40rs", cat: "Snacks", wp: 350, rp: 350, unit: "pc" },
  { name: "Royal Stag 500ml", cat: "Drinks", wp: 120, rp: 120, unit: "pc" },
  { name: "Raii 15kg", cat: "Kirana", wp: 220, rp: 220, unit: "kg" },
  { name: "Classic Regular Cigarette", cat: "Tobacco", wp: 444, rp: 444, unit: "box" },
  { name: "Rajdhani Besan 500g", cat: "Rice & Atta", wp: 50, rp: 50, unit: "pc" },
  { name: "Panni 500gm Pkt", cat: "Stationery", wp: 130, rp: 130, unit: "pkt" },
  { name: "Happy-Happy Biscuit 5rs", cat: "Snacks", wp: 4.38, rp: 4.58, unit: "pc" },
  { name: "Fortune Oil 1kg", cat: "Kirana", wp: 188.5, rp: 195, unit: "kg" },
  { name: "Sweety Supari", cat: "Kirana", wp: 50, rp: 50, unit: "pc" },
  { name: "Vatika Hair Oil 1rs", cat: "Household", wp: 13, rp: 15, unit: "pc" },
  { name: "Gold Flake Lite Cigarette", cat: "Tobacco", wp: 222, rp: 222, unit: "box" },
  { name: "Bhuna Chana", cat: "Kirana", wp: 105, rp: 105, unit: "kg" },
  { name: "Top Ramen Maggie 10rs", cat: "Snacks", wp: 7.29, rp: 7.5, unit: "pc" },
  { name: "Peanuts 10rs", cat: "Snacks", wp: 100, rp: 100, unit: "pc" },
  { name: "Chupa Chups Belt 5rs", cat: "Snacks", wp: 220, rp: 220, unit: "pc" },
  { name: "Coconut Biscuits 10rs", cat: "Snacks", wp: 100, rp: 105, unit: "pc" },
  { name: "Matcha Tea 250gm", cat: "Kirana", wp: 75, rp: 75, unit: "pc" },
  { name: "Radhe Krishn Ghee 500gm", cat: "Kirana", wp: 290, rp: 290, unit: "pc" },
  { name: "Khula Poha Loose", cat: "Kirana", wp: 48, rp: 52, unit: "kg" },
  { name: "Vasmol Hair Colour 35rs", cat: "Household", wp: 31, rp: 31, unit: "pc" },
  { name: "Head & Shoulders 2rs", cat: "Household", wp: 26, rp: 28, unit: "pc" },
  { name: "Badi Elaichi", cat: "Masala", wp: 2200, rp: 2200, unit: "kg" },
  { name: "Hide and Seek Choco Rolls 40rs", cat: "Snacks", wp: 35, rp: 35, unit: "pc" },
  { name: "Eno 10rs Sachet", cat: "Kirana", wp: 8.67, rp: 9, unit: "pc" },
  { name: "Pampers 25rs", cat: "Household", wp: 170, rp: 170, unit: "pc" },
  { name: "Neha Black Henna", cat: "Household", wp: 150, rp: 150, unit: "pc" },
  { name: "Real Juice 20rs", cat: "Drinks", wp: 450, rp: 450, unit: "box" },
  { name: "Barik Magaj", cat: "Kirana", wp: 680, rp: 680, unit: "kg" },
  { name: "Chocos 10rs", cat: "Snacks", wp: 85, rp: 85, unit: "pc" },
  { name: "Maida No.1 500g", cat: "Rice & Atta", wp: 22, rp: 22, unit: "pc" },
  { name: "Kartik Regular Rice 30kg", cat: "Rice & Atta", wp: 48, rp: 48, unit: "kg" },
  { name: "Patanjali Refined Oil Tin 15L", cat: "Kirana", wp: 2300, rp: 2300, unit: "tin" },
  { name: "Gogo Rolling Paper 10rs", cat: "Snacks", wp: 120, rp: 120, unit: "pkt" },
  { name: "Cherry 40gm", cat: "Kirana", wp: 84, rp: 84, unit: "pc" },
  { name: "Mix Achar 5kg", cat: "Kirana", wp: 200, rp: 200, unit: "jar" },
  { name: "Rajshree 5rs", cat: "Snacks", wp: 130, rp: 130, unit: "pc" },
  { name: "Snakkers 5rs", cat: "Snacks", wp: 130, rp: 130, unit: "pc" },
  { name: "Orange Bite Toffees 50rs", cat: "Snacks", wp: 40, rp: 40, unit: "pkt" },
  { name: "Khajoor Kamia Gold", cat: "Kirana", wp: 200, rp: 200, unit: "pc" },
  { name: "Rajdhani Atta 10kg", cat: "Rice & Atta", wp: 360, rp: 360, unit: "kg" },
  { name: "Neeraj Mehendi 100gm", cat: "Household", wp: 39, rp: 39, unit: "pc" },
  { name: "Punjabi Mixture 5rs", cat: "Snacks", wp: 52, rp: 52, unit: "pc" },
  { name: "Johnson Baby Oil 70rs", cat: "Household", wp: 63, rp: 63, unit: "pc" },
  { name: "Frooti 2L Bottle", cat: "Drinks", wp: 83.33, rp: 83.33, unit: "pc" },
  { name: "Pasta Loose", cat: "Kirana", wp: 60, rp: 65, unit: "kg" },
  { name: "Vasmol Hair Oil 65rs", cat: "Household", wp: 58, rp: 60, unit: "pc" },
  { name: "Dabur Red Paste 100gm", cat: "Kirana", wp: 50, rp: 50, unit: "pc" },
  { name: "Monaco Achari 10rs", cat: "Snacks", wp: 108, rp: 108, unit: "pc" },
  { name: "Frooti 10rs", cat: "Drinks", wp: 8, rp: 8, unit: "pc" },
  { name: "Raang Kesar 100gm", cat: "Kirana", wp: 35, rp: 35, unit: "pc" },
  { name: "Khand Packet", cat: "Kirana", wp: 78, rp: 78, unit: "pc" },
  { name: "Dove Shampoo 220ml", cat: "Household", wp: 200, rp: 200, unit: "pc" },
  { name: "Rajdhani Mota Besan", cat: "Kirana", wp: 82, rp: 85, unit: "kg" },
  { name: "Bajaj Almond Drops 50ml", cat: "Household", wp: 39, rp: 40, unit: "pc" },
  { name: "Gold Flake Smart Cigarette", cat: "Tobacco", wp: 100, rp: 100, unit: "box" },
  { name: "Haridarshan Dhoop 10rs", cat: "Household", wp: 225, rp: 230, unit: "box" },
  { name: "Nut Cracker 5rs", cat: "Snacks", wp: 52, rp: 52, unit: "pc" },
  { name: "Fair & Lovely Face Wash 50ml", cat: "Household", wp: 90, rp: 90, unit: "pc" },
  { name: "Hide and Seek 75rs", cat: "Snacks", wp: 65, rp: 75, unit: "pc" },
  { name: "Parle G 4rs", cat: "Snacks", wp: 94, rp: 94, unit: "box" },
  { name: "Surf Excel Soap 42rs", cat: "Household", wp: 38, rp: 38, unit: "pc" },
  { name: "Surf Excel 1kg", cat: "Household", wp: 130, rp: 135, unit: "kg" },
  { name: "Haldi Powder 100g", cat: "Masala", wp: 40, rp: 40, unit: "pc" },
  { name: "Kaju Char Phad", cat: "Kirana", wp: 780, rp: 820, unit: "kg" },
  { name: "Dettol Antiseptic 50ml", cat: "Household", wp: 40, rp: 40, unit: "pc" },
  { name: "Dibba Lighter Box", cat: "Kirana", wp: 360, rp: 360, unit: "box" },
  { name: "Jeera 100gm", cat: "Masala", wp: 32, rp: 42, unit: "pc" },
  { name: "Sprite 2L Bottle", cat: "Drinks", wp: 680, rp: 680, unit: "box" },
  { name: "Moong Dal 5rs", cat: "Snacks", wp: 52, rp: 52, unit: "pc" },
  { name: "Dettol Soap 10rs", cat: "Household", wp: 9, rp: 9, unit: "pc" },
  { name: "Whisper Sanitary Pads 40rs", cat: "Household", wp: 35, rp: 35, unit: "pc" },
  { name: "Gajini Rice 30kg", cat: "Rice & Atta", wp: 35, rp: 35, unit: "kg" },
  { name: "Tops Green Chilli Sauce", cat: "Kirana", wp: 15, rp: 15, unit: "pc" },
  { name: "Khand Khulli 50kg", cat: "Rice & Atta", wp: 68, rp: 68, unit: "kg" },
  { name: "Double Burst Cigarette", cat: "Tobacco", wp: 444, rp: 444, unit: "box" },
  { name: "Minute Maid Pulpy Orange 250ml", cat: "Drinks", wp: 520, rp: 520, unit: "box" },
  { name: "Soyabean 10rs", cat: "Snacks", wp: 70, rp: 70, unit: "pc" },
  { name: "Dhaniya Powder 1kg", cat: "Masala", wp: 250, rp: 290, unit: "kg" },
  { name: "Chicken Masala 100g", cat: "Masala", wp: 76, rp: 76, unit: "pc" },
  { name: "Whisper Sanitary Pads 45rs", cat: "Household", wp: 40, rp: 40, unit: "pc" },
  { name: "Andaz Rice", cat: "Rice & Atta", wp: 36.67, rp: 36.67, unit: "kg" },
  { name: "Dettol Handwash 99rs", cat: "Household", wp: 90, rp: 90, unit: "pc" },
  { name: "Down Free Sanitary Pads 40rs", cat: "Household", wp: 25, rp: 25, unit: "pc" },
  { name: "Fanta 1L Bottle", cat: "Drinks", wp: 630, rp: 630, unit: "box" },
  { name: "Uncle Chips 5rs", cat: "Snacks", wp: 54, rp: 54, unit: "pc" },
  { name: "Marlboro Lite Cigarette", cat: "Tobacco", wp: 444, rp: 444, unit: "box" },
  { name: "Ghadi Detergent Surf 1kg", cat: "Household", wp: 68.44, rp: 70, unit: "kg" },
  { name: "Parachute Coconut Oil 200ml", cat: "Household", wp: 110, rp: 110, unit: "pc" },
  { name: "Z Black Dhoop 10rs", cat: "Household", wp: 100, rp: 110, unit: "box" },
  { name: "Peanuts Roasted 200gm", cat: "Snacks", wp: 54, rp: 54, unit: "pc" },
  { name: "Ocean Tea Special 250gm", cat: "Kirana", wp: 90, rp: 90, unit: "pc" },
  { name: "Bingo Mad Angles 10rs", cat: "Snacks", wp: 108, rp: 108, unit: "pc" },
  { name: "Kala Namak 200gm", cat: "Kirana", wp: 10, rp: 10, unit: "pc" },
  { name: "Surf Excel 10rs", cat: "Household", wp: 8.6, rp: 8.75, unit: "pc" },
  { name: "Butter Delight Biscuits 10rs", cat: "Snacks", wp: 90, rp: 90, unit: "pc" },
  { name: "Aluminium Foil Pouch 100gm", cat: "Stationery", wp: 50, rp: 50, unit: "pc" },
  { name: "Fanta 20rs Can/Bottle", cat: "Drinks", wp: 500, rp: 500, unit: "box" },
  { name: "Ponds Cold Cream 6ml", cat: "Household", wp: 330, rp: 330, unit: "box" },
  { name: "Dabur Amla Hair Oil 10rs", cat: "Household", wp: 8.75, rp: 9, unit: "pc" },
  { name: "Kali Sarso Mustard", cat: "Kirana", wp: 120, rp: 120, unit: "kg" },
  { name: "Jasmine Hair Oil 95rs", cat: "Household", wp: 85, rp: 90, unit: "pc" },
  { name: "Dairy Milk 5rs", cat: "Snacks", wp: 335, rp: 335, unit: "box" },
  { name: "Rajma Masala", cat: "Masala", wp: 72, rp: 72, unit: "pc" },
  { name: "Lays Cream & Onion Green 5rs", cat: "Snacks", wp: 54, rp: 56, unit: "pc" },
  { name: "Deep Ghee 500ml", cat: "Kirana", wp: 88, rp: 88, unit: "pc" },
  { name: "Mishri Dhaga", cat: "Masala", wp: 100, rp: 100, unit: "kg" },
  { name: "Crunchy Namkeen 5rs", cat: "Snacks", wp: 54, rp: 54, unit: "pc" },
  { name: "Lays Green 25rs", cat: "Snacks", wp: 17.5, rp: 17.5, unit: "pc" },
  { name: "Sabudana Papad", cat: "Kirana", wp: 110, rp: 110, unit: "kg" },
  { name: "Dalbiji 10rs", cat: "Snacks", wp: 100, rp: 100, unit: "pc" },
  { name: "Patanjali Dant Kanti 20rs", cat: "Kirana", wp: 18, rp: 18, unit: "pc" },
  { name: "Sendha Namak Rock Salt 1kg", cat: "Kirana", wp: 45, rp: 45, unit: "kg" },
  { name: "Nescafe Coffee 2rs", cat: "Kirana", wp: 260, rp: 260, unit: "box" },
  { name: "Park Avenue Deo 120ml", cat: "Household", wp: 160, rp: 160, unit: "pc" },
  { name: "Hing R Pure 130rs", cat: "Masala", wp: 110, rp: 115, unit: "pc" },
  { name: "Close Up Toothpaste 10rs", cat: "Kirana", wp: 105, rp: 105, unit: "box" },
  { name: "Glass 350ml Cups", cat: "Stationery", wp: 35, rp: 35, unit: "pkt" },
  { name: "Ponds Body Lotion 379rs", cat: "Household", wp: 280, rp: 280, unit: "pc" },
  { name: "Tata Tea Premium 250g", cat: "Kirana", wp: 108, rp: 108, unit: "pc" },
  { name: "Jasmine Hair Oil 20rs", cat: "Household", wp: 18, rp: 18, unit: "pc" },
  { name: "Boora Special Sugar", cat: "Kirana", wp: 78, rp: 78, unit: "kg" },
  { name: "Vimal Pan Masala", cat: "Tobacco", wp: 130, rp: 130, unit: "pc" },
  { name: "Notebook English Ruled", cat: "Stationery", wp: 180, rp: 180, unit: "pkt" },
  { name: "Rajdhani Makka Atta 1kg", cat: "Rice & Atta", wp: 44, rp: 44, unit: "kg" },
  { name: "Lays Green 20rs", cat: "Snacks", wp: 17.5, rp: 17.5, unit: "pc" },
  { name: "Amul Spray Milk Powder", cat: "Kirana", wp: 24, rp: 24, unit: "pc" },
  { name: "Nip Dishwash 75rs", cat: "Household", wp: 60, rp: 60, unit: "pc" },
  { name: "All in One Mixture 5rs", cat: "Snacks", wp: 52, rp: 52, unit: "pc" },
  { name: "Kachri Papad", cat: "Kirana", wp: 300, rp: 300, unit: "kg" },
  { name: "Limca 2L Bottle", cat: "Drinks", wp: 75.56, rp: 75.56, unit: "pc" },
  { name: "Dahi Bhalla Masala 100g", cat: "Masala", wp: 79, rp: 79, unit: "pc" },
  { name: "Rajdhani Sattu 500g", cat: "Rice & Atta", wp: 55, rp: 55, unit: "pc" },
  { name: "Sooji No.1 500gm", cat: "Rice & Atta", wp: 22, rp: 22, unit: "pc" },
  { name: "Nova Cardamom Elaichi 10rs", cat: "Kirana", wp: 320, rp: 320, unit: "box" },
  { name: "Tata Salt 10rs", cat: "Kirana", wp: 350, rp: 350, unit: "box" },
  { name: "Tide Surf Detergent 5kg", cat: "Household", wp: 550, rp: 550, unit: "kg" },
  { name: "Real Guava Juice 1L", cat: "Drinks", wp: 1080, rp: 1080, unit: "box" },
  { name: "Safed Dakhni Mirch 500gm", cat: "Masala", wp: 700, rp: 700, unit: "g" },
  { name: "Poha No.1 500g", cat: "Rice & Atta", wp: 38, rp: 38, unit: "pc" },
  { name: "Sprite 750ml Bottle", cat: "Drinks", wp: 750, rp: 750, unit: "box" },
  { name: "Lucknowi Sauf 100gm", cat: "Masala", wp: 40, rp: 40, unit: "pc" },
  { name: "Vicks Inhaler/Balm Jar", cat: "Kirana", wp: 140, rp: 180, unit: "jar" },
  { name: "Alpenliebe Just Jelly Jar", cat: "Snacks", wp: 200, rp: 200, unit: "jar" },
  { name: "Indimint Cigarette", cat: "Tobacco", wp: 110, rp: 110, unit: "box" },
  { name: "Bhujiya 60rs", cat: "Snacks", wp: 54, rp: 54, unit: "pc" },
  { name: "Maxo Mosquito Set", cat: "Household", wp: 80, rp: 80, unit: "set" },
  { name: "Fortune Refined Oil 13L", cat: "Kirana", wp: 1300, rp: 1350, unit: "tin" },
  { name: "Boondi 200gm", cat: "Snacks", wp: 50, rp: 50, unit: "pc" },
  { name: "Lays Spanish Tomato Tango Red 20rs", cat: "Snacks", wp: 17.5, rp: 17.5, unit: "pc" },
  { name: "Nip Dishwash Bar 5rs", cat: "Household", wp: 4.5, rp: 4.5, unit: "pc" },
  { name: "Surf Excel Bar 10rs", cat: "Household", wp: 9, rp: 9, unit: "pc" },
  { name: "Act II Popcorn 10rs", cat: "Snacks", wp: 80, rp: 80, unit: "box" },
  { name: "Tiger Glucose Biscuits 5rs", cat: "Snacks", wp: 108, rp: 108, unit: "box" },
  { name: "Lizol Floor Cleaner 500ml", cat: "Household", wp: 112, rp: 120, unit: "pc" },
  { name: "AK Gold Basmati Rice", cat: "Rice & Atta", wp: 42.31, rp: 42.31, unit: "kg" },
  { name: "Ganesh Atta 5kg", cat: "Rice & Atta", wp: 156, rp: 156, unit: "kg" },
  { name: "Butter Delight 5rs", cat: "Snacks", wp: 44, rp: 45, unit: "pc" },
  { name: "Roasted Peanuts Crusher 10rs", cat: "Snacks", wp: 100, rp: 100, unit: "pc" },
  { name: "Garnier Vitamin C Face Wash 50ml", cat: "Household", wp: 90, rp: 90, unit: "pc" },
  { name: "Lifebuoy Soap Set", cat: "Household", wp: 140, rp: 145, unit: "set" },
  { name: "Bisleri Water 1L", cat: "Drinks", wp: 130, rp: 130, unit: "box" },
  { name: "Barik Besan Rajdhani 35kg", cat: "Rice & Atta", wp: 3040, rp: 3040, unit: "kg" },
  { name: "Aamla Sukha Dry", cat: "Kirana", wp: 180, rp: 180, unit: "kg" },
  { name: "Soya Chunks Big 200g", cat: "Kirana", wp: 40, rp: 40, unit: "pc" },
  { name: "Cadbury Dairy Milk 45rs", cat: "Snacks", wp: 1215, rp: 1215, unit: "box" },
  { name: "Pasta Pouch 20rs", cat: "Kirana", wp: 17, rp: 17, unit: "pc" },
  { name: "Hide and Seek 40rs", cat: "Snacks", wp: 36, rp: 36, unit: "pc" },
  { name: "Ajwain Carom Seeds", cat: "Masala", wp: 220, rp: 220, unit: "kg" },
  { name: "Maggi Masala 5rs Sachet", cat: "Snacks", wp: 4.5, rp: 4.8, unit: "pc" },
  { name: "Harpic Toilet Cleaner 110rs", cat: "Household", wp: 100, rp: 100, unit: "pc" },
  { name: "Red Label Tea 270rs", cat: "Kirana", wp: 248, rp: 248, unit: "pc" },
  { name: "Ponds Body Lotion 90ml", cat: "Household", wp: 105, rp: 105, unit: "pc" },
  { name: "Shiv Bidi 10rs", cat: "Tobacco", wp: 145, rp: 145, unit: "pkt" },
  { name: "Saunth Ginger Powder Loose", cat: "Masala", wp: 480, rp: 480, unit: "kg" },
  { name: "Pili Mirch Yellow Chilli 500gm", cat: "Masala", wp: 240, rp: 240, unit: "g" },
  { name: "Hide and Seek 45rs", cat: "Snacks", wp: 40, rp: 40, unit: "pc" },
  { name: "Kaju Do Phad Split Cashews", cat: "Kirana", wp: 850, rp: 910, unit: "kg" },
  { name: "Chilli Lemon Namkeen 20rs", cat: "Snacks", wp: 17.5, rp: 17.5, unit: "pc" },
  { name: "Ponds Cold Cream 5rs", cat: "Household", wp: 290, rp: 290, unit: "box" },
  { name: "Vaseline Body Lotion 90rs", cat: "Household", wp: 80, rp: 80, unit: "pc" },
  { name: "Imli Tamarind 200gm", cat: "Masala", wp: 30, rp: 30, unit: "pc" },
  { name: "Parle 20-20 Gold 50rs", cat: "Snacks", wp: 45, rp: 45, unit: "pc" },
  { name: "Cinthol Soap Set", cat: "Household", wp: 150, rp: 150, unit: "set" },
  { name: "Jawa Vermicelli 500g", cat: "Kirana", wp: 50, rp: 50, unit: "pc" },
  { name: "Moong Dal Namkeen 10rs", cat: "Snacks", wp: 100, rp: 100, unit: "pc" },
  { name: "Cadbury Dairy Milk 10rs", cat: "Snacks", wp: 510, rp: 510, unit: "box" },
  { name: "Boroplus Prickly Heat Powder 10rs", cat: "Household", wp: 420, rp: 420, unit: "box" },
  { name: "MDH Haldi Powder 500gm", cat: "Masala", wp: 200, rp: 200, unit: "pc" },
  { name: "Besan 200g Pkt", cat: "Rice & Atta", wp: 20.4, rp: 21, unit: "pc" },
  { name: "Thums Up 1L Bottle", cat: "Drinks", wp: 630, rp: 630, unit: "box" },
  { name: "Lays Classic Salted 10rs", cat: "Snacks", wp: 108, rp: 108, unit: "pc" },
  { name: "Macaroni Pasta", cat: "Kirana", wp: 65, rp: 70, unit: "kg" },
  { name: "Patanjali Doodh Biscuit 5rs", cat: "Snacks", wp: 90, rp: 90, unit: "box" },
  { name: "Pepsi 400ml Bottle", cat: "Drinks", wp: 520, rp: 520, unit: "box" },
  { name: "Mentos Mint Jar", cat: "Snacks", wp: 190, rp: 190, unit: "jar" },
  { name: "Cadbury Dairy Milk 20rs", cat: "Snacks", wp: 720, rp: 720, unit: "box" },
  { name: "Hair & Care Hair Oil 100ml", cat: "Household", wp: 60, rp: 60, unit: "pc" },
  { name: "Vicks VapoRub 23rs", cat: "Kirana", wp: 19, rp: 19, unit: "pc" },
  { name: "Dabur Honey 50gm", cat: "Kirana", wp: 41, rp: 41, unit: "pc" },
  { name: "Shikhar Pan Masala 20rs", cat: "Tobacco", wp: 195, rp: 195, unit: "pkt" },
  { name: "Godrej Expert Hair Dye 200rs", cat: "Household", wp: 190, rp: 190, unit: "pc" },
  { name: "Nimbu Masala Namkeen 10rs", cat: "Snacks", wp: 100, rp: 100, unit: "pc" },
  { name: "Matchbox Machis 5rs Bundle", cat: "Household", wp: 45, rp: 45, unit: "pkt" },
  { name: "Odomos Mosquito Cream 50gm", cat: "Household", wp: 58, rp: 58, unit: "pc" },
  { name: "Diet Mixture 5rs", cat: "Snacks", wp: 52, rp: 52, unit: "pc" },
  { name: "Agarbatti Incense 10rs", cat: "Household", wp: 100, rp: 100, unit: "pkt" },
  { name: "Mountain Dew 750ml", cat: "Drinks", wp: 25, rp: 25, unit: "pc" },
  { name: "Haldi Powder 50gm", cat: "Masala", wp: 13, rp: 17, unit: "pc" },
  { name: "Sunsilk Shampoo 68rs", cat: "Household", wp: 62, rp: 62, unit: "pc" },
  { name: "Margo Neem Soap 10rs", cat: "Household", wp: 9, rp: 9, unit: "pc" },
  { name: "Malka Sabut Lentils", cat: "Kirana", wp: 85, rp: 90, unit: "kg" },
  { name: "Sabut Akhrot Walnuts 500gm", cat: "Kirana", wp: 290, rp: 290, unit: "g" },
  { name: "Close Up Toothpaste 100gm", cat: "Household", wp: 50, rp: 50, unit: "pc" },
  { name: "Colgate Toothbrush 20rs", cat: "Household", wp: 17.5, rp: 18, unit: "pc" },
  { name: "Fena Detergent Powder 1kg", cat: "Household", wp: 67, rp: 68, unit: "kg" },
  { name: "Garnier Face Wash 50ml", cat: "Household", wp: 104, rp: 110, unit: "pc" },
  { name: "Chaat Masala 1kg", cat: "Masala", wp: 90, rp: 90, unit: "kg" },
  { name: "Bisleri Water 250ml", cat: "Drinks", wp: 5.42, rp: 5.42, unit: "pc" },
  { name: "Punjabi Tadka Namkeen 200gm", cat: "Snacks", wp: 47, rp: 47, unit: "pc" },
  { name: "Kali Mirch Black Pepper 10rs", cat: "Masala", wp: 80, rp: 90, unit: "box" },
  { name: "Crax Fritts 5rs", cat: "Snacks", wp: 62, rp: 62, unit: "box" },
  { name: "Hide and Seek 30rs", cat: "Snacks", wp: 450, rp: 450, unit: "box" },
  { name: "Alpenliebe Toffee Jar", cat: "Snacks", wp: 188, rp: 188, unit: "jar" },
  { name: "Til Ka Tel Sesame Oil 1L", cat: "Kirana", wp: 124, rp: 124, unit: "l" },
  { name: "Meat Masala 100g", cat: "Masala", wp: 80, rp: 80, unit: "pc" },
  { name: "Kuber Khaini 10rs", cat: "Tobacco", wp: 245, rp: 245, unit: "box" },
  { name: "Happy Dent Chewing Gum Jar", cat: "Snacks", wp: 190, rp: 190, unit: "jar" },
  { name: "Mahadev Sev 500g", cat: "Kirana", wp: 370, rp: 380, unit: "pc" },
  { name: "Bhujiya 10rs Pkt", cat: "Snacks", wp: 100, rp: 100, unit: "pc" },
  { name: "Dabur Mustard Oil 10rs", cat: "Kirana", wp: 8.75, rp: 8.75, unit: "pc" },
  { name: "AA Battery Cells (Pair)", cat: "Stationery", wp: 140, rp: 140, unit: "box" },
  { name: "Tide Detergent 500g", cat: "Household", wp: 58, rp: 58, unit: "pc" },
  { name: "Famous Washing Soap", cat: "Household", wp: 75, rp: 85, unit: "box" },
  { name: "Jasmine Coconut Oil 500ml", cat: "Household", wp: 300, rp: 310, unit: "pc" },
  { name: "Goond Edible Gum", cat: "Kirana", wp: 280, rp: 280, unit: "kg" },
  { name: "Sprite 250ml Can/Bottle", cat: "Drinks", wp: 500, rp: 500, unit: "box" },
  { name: "Good Knight Mosquito Liquid 85rs", cat: "Household", wp: 75, rp: 75, unit: "pc" },
  { name: "Batasa Sugar Drops 5kg", cat: "Kirana", wp: 400, rp: 400, unit: "kg" },
  { name: "Ganesh Atta 10kg", cat: "Rice & Atta", wp: 310, rp: 310, unit: "kg" },
  { name: "Deep Ghee 200ml", cat: "Kirana", wp: 38, rp: 38, unit: "pc" },
  { name: "Choco Roll 10rs", cat: "Snacks", wp: 140, rp: 140, unit: "box" },
  { name: "Diet Namkeen 10rs", cat: "Snacks", wp: 100, rp: 100, unit: "pc" },
  { name: "Chaat Masala 500gm", cat: "Masala", wp: 100, rp: 100, unit: "g" },
  { name: "Sunsilk Shampoo 345rs", cat: "Household", wp: 300, rp: 300, unit: "pc" },
  { name: "Nova Chai Tea 10rs", cat: "Kirana", wp: 440, rp: 440, unit: "box" },
  { name: "Dermi Cool Prickly Heat Powder 55rs", cat: "Household", wp: 50, rp: 50, unit: "pc" },
  { name: "Punjabi Mixture 10rs", cat: "Snacks", wp: 100, rp: 100, unit: "pc" },
  { name: "Oyes Snacks (60 Pcs Box)", cat: "Snacks", wp: 260, rp: 260, unit: "box" },
  { name: "Parle Melody Toffee Pouch 100rs", cat: "Snacks", wp: 90, rp: 90, unit: "pkt" },
  { name: "Aluminium Foil 100gm Roll", cat: "Stationery", wp: 50, rp: 50, unit: "pc" },
  { name: "Funtop Tomato Ketchup Sauce 1L", cat: "Kirana", wp: 85, rp: 85, unit: "pc" },
  { name: "Funtop Soya Sauce 1L", cat: "Kirana", wp: 70, rp: 70, unit: "pc" },
  { name: "Today Tea 10rs", cat: "Kirana", wp: 9.38, rp: 9.38, unit: "pc" },
  { name: "Lays Classic Salted Yellow 10rs", cat: "Snacks", wp: 108, rp: 108, unit: "pc" },
  { name: "Ghadi Detergent Soap 10rs", cat: "Household", wp: 9, rp: 9, unit: "pc" },
  { name: "Nut Cracker Namkeen 10rs", cat: "Snacks", wp: 100, rp: 100, unit: "pc" },
  { name: "Elaichi Pearls Mouth Freshener 10rs", cat: "Kirana", wp: 110, rp: 110, unit: "box" },
  { name: "Khaskhas Poppy Seeds 100gm", cat: "Masala", wp: 160, rp: 160, unit: "pc" },
  { name: "Hit Mosquito Spray 700ml", cat: "Household", wp: 260, rp: 260, unit: "pc" },
  { name: "Appy Fizz 10rs", cat: "Drinks", wp: 8.75, rp: 8.75, unit: "pc" },
  { name: "All in One Mixture 200gm", cat: "Snacks", wp: 54, rp: 54, unit: "pc" },
  { name: "Aashirvaad Shudh Chakki Atta 5kg", cat: "Rice & Atta", wp: 228, rp: 228, unit: "kg" },
  { name: "570 Bidi Bundle", cat: "Tobacco", wp: 270, rp: 270, unit: "pkt" },
  { name: "Rangkat Papdi 100gm", cat: "Masala", wp: 40, rp: 40, unit: "pc" },
  { name: "Fena Detergent 500g", cat: "Household", wp: 34.5, rp: 36, unit: "pc" },
  { name: "Neha Red Mehendi Cone", cat: "Household", wp: 150, rp: 150, unit: "box" },
  { name: "Mahadev Bhujia 500g", cat: "Kirana", wp: 370, rp: 380, unit: "pc" },
  { name: "Nataraj Pencil Box", cat: "Stationery", wp: 35, rp: 35, unit: "box" },
  { name: "Compounded Asafoetida Hing Jar", cat: "Masala", wp: 400, rp: 400, unit: "jar" },
  { name: "Nutrifresh Atta 10kg", cat: "Rice & Atta", wp: 1690, rp: 1690, unit: "kg" },
  { name: "Dalda Vanaspati Ghee 500ml", cat: "Kirana", wp: 81, rp: 81, unit: "pc" },
  { name: "Kurkure Chatpata 5rs", cat: "Snacks", wp: 54, rp: 54, unit: "pc" },
  { name: "Urad Sabut Whole Black Gram", cat: "Kirana", wp: 112, rp: 112, unit: "kg" },
  { name: "Dove Beauty Bar Soap 25rs", cat: "Household", wp: 22.5, rp: 22.5, unit: "pc" },
  { name: "Pasta Pouch 5rs", cat: "Kirana", wp: 60, rp: 60, unit: "box" },
  { name: "Pav Bhaji Masala 100g", cat: "Masala", wp: 77, rp: 77, unit: "pc" },
  { name: "Green Chilli Sauce 5L Can", cat: "Kirana", wp: 250, rp: 250, unit: "can" },
  { name: "Khatta Meetha Namkeen 200gm", cat: "Snacks", wp: 45, rp: 45, unit: "pc" },
  { name: "Krishn Desi Ghee 500gm", cat: "Kirana", wp: 290, rp: 290, unit: "pc" },
  { name: "Ginger Garlic Adrak Paste", cat: "Kirana", wp: 120, rp: 120, unit: "pc" },
  { name: "Dabur Hajmola Big Jar", cat: "Kirana", wp: 400, rp: 400, unit: "jar" },
  { name: "Catch Soda Cans/Bottles", cat: "Drinks", wp: 360, rp: 360, unit: "box" },
  { name: "Horlicks Chocolate 1kg", cat: "Kirana", wp: 360, rp: 360, unit: "pc" },
  { name: "Melody Toffee Pouch 50rs", cat: "Snacks", wp: 45, rp: 45, unit: "pkt" },
  { name: "Om Premium Rusk Toast", cat: "Snacks", wp: 390, rp: 390, unit: "box" },
  { name: "Dhaniya Coriander Powder 1kg", cat: "Masala", wp: 250, rp: 260, unit: "kg" },
  { name: "Colgate Strong Teeth 200gm", cat: "Household", wp: 130, rp: 130, unit: "pc" },
  { name: "Cadbury Oreo Biscuits 10rs", cat: "Snacks", wp: 108, rp: 108, unit: "pc" },
  { name: "Sewak Basmati Rice", cat: "Rice & Atta", wp: 46.15, rp: 46.15, unit: "kg" },
  { name: "Uncle Chips 20rs", cat: "Snacks", wp: 18, rp: 18, unit: "pc" },
  { name: "Frooti Mango Drink 600ml", cat: "Drinks", wp: 28.33, rp: 28.33, unit: "pc" },
  { name: "Kurkure Hyderabadi Hungama 5rs", cat: "Snacks", wp: 50, rp: 52, unit: "pc" },
  { name: "Britannia 50-50 Maska Chaska 10rs", cat: "Snacks", wp: 9, rp: 9, unit: "pc" },
  { name: "Food Colour Peela Yellow 100gm", cat: "Kirana", wp: 35, rp: 35, unit: "pc" },
  { name: "Hell Energy Drink 250ml Can", cat: "Drinks", wp: 52.5, rp: 52.5, unit: "pc" },
  { name: "Frooti Mango Drink 20rs", cat: "Drinks", wp: 17.33, rp: 17.33, unit: "pc" },
  { name: "Polythene Panni 1kg Pkt", cat: "Stationery", wp: 130, rp: 130, unit: "pkt" },
  { name: "Safed Til White Sesame", cat: "Kirana", wp: 160, rp: 160, unit: "kg" },
  { name: "Odomos Mosquito Cream 120rs", cat: "Household", wp: 105, rp: 105, unit: "pc" },
  { name: "Funtop Tomato Sauce 500ml", cat: "Kirana", wp: 48, rp: 48, unit: "pc" },
  { name: "Makhana Foxnuts 250g", cat: "Kirana", wp: 250, rp: 250, unit: "g" },
  { name: "Nestle Munch Chocolate 5rs", cat: "Snacks", wp: 4.38, rp: 4.38, unit: "pc" },
  { name: "Sanitary Pads 90rs", cat: "Household", wp: 80, rp: 80, unit: "pc" },
  { name: "Parachute Coconut Oil 10rs", cat: "Household", wp: 8.75, rp: 8.75, unit: "pc" },
  { name: "Maaza Mango Drink 250ml", cat: "Drinks", wp: 8.33, rp: 8.33, unit: "pc" },
  { name: "Kurkure Puffcorn 10rs", cat: "Snacks", wp: 10.8, rp: 10.8, unit: "pc" },
  { name: "Macaroni 200g", cat: "Kirana", wp: 16, rp: 16, unit: "pc" },
  { name: "Navratna Ayurvedic Oil 300ml", cat: "Household", wp: 210, rp: 210, unit: "pc" },
  { name: "Red Chilli Mirch Powder", cat: "Masala", wp: 34, rp: 40, unit: "pc" },
  { name: "Aashirvaad Shudh Chakki Atta 10kg", cat: "Rice & Atta", wp: 441, rp: 441, unit: "kg" },
  { name: "Murmura Puffed Rice 500g", cat: "Kirana", wp: 35, rp: 35, unit: "pc" },
  { name: "Laxman Rekha Cockroach Chalk", cat: "Household", wp: 140, rp: 140, unit: "box" },
  { name: "Parle G Biscuits 5rs", cat: "Snacks", wp: 106, rp: 106, unit: "box" },
  { name: "Patanjali Dant Kanti 200gm", cat: "Household", wp: 105, rp: 105, unit: "pc" },
  { name: "Odomos Cream 60rs", cat: "Household", wp: 50, rp: 50, unit: "pc" },
  { name: "Godrej No.1 Soap Set", cat: "Household", wp: 103, rp: 110, unit: "set" },
  { name: "Biryani King Basmati Rice", cat: "Rice & Atta", wp: 95, rp: 95, unit: "kg" },
  { name: "Britannia Marigold Biscuits 10rs", cat: "Snacks", wp: 9, rp: 9, unit: "pc" },
  { name: "Bingo Tedhe Medhe 10rs", cat: "Snacks", wp: 10.5, rp: 10.5, unit: "pc" },
  { name: "Pitambari Shining Powder", cat: "Household", wp: 40, rp: 40, unit: "pc" },
  { name: "Vaseline Petroleum Jelly 5rs", cat: "Household", wp: 210, rp: 210, unit: "box" },
  { name: "Crax Curls Rings 10rs", cat: "Snacks", wp: 8.75, rp: 9, unit: "pc" },
  { name: "Impact Surf Detergent 1kg", cat: "Household", wp: 105, rp: 105, unit: "kg" },
  { name: "LED Emergency Charging Bulb", cat: "Household", wp: 300, rp: 300, unit: "pc" },
  { name: "Kitchen King Masala 100g", cat: "Masala", wp: 80, rp: 80, unit: "pc" },
  { name: "Hit Flying Insect Spray Red 110rs", cat: "Household", wp: 100, rp: 100, unit: "pc" },
  { name: "Parle G Biscuits 10rs", cat: "Snacks", wp: 105, rp: 105, unit: "box" },
  { name: "Fena Detergent Soap 10rs", cat: "Household", wp: 7.5, rp: 8, unit: "pc" },
  { name: "Krishna Bidi Bundle", cat: "Tobacco", wp: 150, rp: 150, unit: "pkt" },
  { name: "Rajshree Pan Masala 60rs", cat: "Tobacco", wp: 375, rp: 375, unit: "box" },
  { name: "Johnson Baby Oil 50ml", cat: "Household", wp: 125, rp: 125, unit: "pc" },
  { name: "Kala Namak Black Salt 1kg", cat: "Kirana", wp: 50, rp: 50, unit: "kg" },
  { name: "Patanjali Doodh Biscuits 10rs", cat: "Snacks", wp: 90, rp: 90, unit: "box" },
  { name: "Moongfali Peanuts Dana", cat: "Kirana", wp: 120, rp: 125, unit: "kg" },
  { name: "Fair & Handsome Cream 15gm", cat: "Household", wp: 35, rp: 35, unit: "pc" },
  { name: "Vim Dishwash Gel 15rs", cat: "Household", wp: 13.5, rp: 13.5, unit: "pc" },
  { name: "Mountain Dew 400ml Bottle", cat: "Drinks", wp: 17.67, rp: 17.67, unit: "pc" },
  { name: "Red Bull Energy Drink 250ml", cat: "Drinks", wp: 2300, rp: 2300, unit: "box" },
  { name: "Milkfood Pure Ghee 1kg", cat: "Kirana", wp: 540, rp: 540, unit: "kg" },
  { name: "Limca 1L Bottle", cat: "Drinks", wp: 42, rp: 42, unit: "pc" },
  { name: "MDH Garam Masala 100gm", cat: "Masala", wp: 92, rp: 92, unit: "pc" },
  { name: "Oregano Flakes 1kg", cat: "Masala", wp: 240, rp: 240, unit: "kg" },
  { name: "Crax Curls 5rs", cat: "Snacks", wp: 44, rp: 44, unit: "box" },
  { name: "Soyabean Moti 5kg", cat: "Kirana", wp: 475, rp: 475, unit: "kg" },
  { name: "Kala Til Black Sesame", cat: "Kirana", wp: 160, rp: 180, unit: "kg" },
  { name: "Laung Cloves Whole", cat: "Masala", wp: 1100, rp: 1100, unit: "kg" },
  { name: "Ezee Liquid Detergent 120rs", cat: "Household", wp: 108, rp: 108, unit: "pc" },
  { name: "Gulabari Gulab Jal 120ml", cat: "Household", wp: 47, rp: 47, unit: "pc" },
  { name: "Blue Ballpoint Pen", cat: "Stationery", wp: 20, rp: 20, unit: "pc" },
  { name: "Haldiram Boondi 10rs", cat: "Snacks", wp: 100, rp: 100, unit: "pc" },
  { name: "Krishn Desi Ghee 1kg", cat: "Kirana", wp: 600, rp: 600, unit: "kg" },
  { name: "Dove Soap 2rs Mini", cat: "Household", wp: 24, rp: 24, unit: "pc" },
  { name: "Sauf Mithi Sweet Fennel 1kg", cat: "Kirana", wp: 240, rp: 240, unit: "kg" },
  { name: "Jayfal Nutmeg 500gm", cat: "Masala", wp: 480, rp: 480, unit: "g" },
  { name: "Lobhiya Black Eyed Beans", cat: "Kirana", wp: 120, rp: 130, unit: "kg" },
  { name: "Rajdhani Besan 200gm", cat: "Rice & Atta", wp: 22, rp: 22, unit: "pc" },
  { name: "Four-1 Refined Oil 1L", cat: "Kirana", wp: 158.37, rp: 160, unit: "l" },
  { name: "Hing Chana Masala 10rs", cat: "Snacks", wp: 100, rp: 100, unit: "pc" },
  { name: "Toothbrush Card Pack 20rs", cat: "Household", wp: 140, rp: 140, unit: "box" },
  { name: "Godrej No.1 Soap 120rs Pack", cat: "Household", wp: 108, rp: 108, unit: "set" },
  { name: "Rajdhani Chakki Atta 5kg", cat: "Rice & Atta", wp: 184, rp: 184, unit: "kg" },
  { name: "Navratan Namkeen 5rs", cat: "Snacks", wp: 52, rp: 52, unit: "pc" },
  { name: "Lays Magic Masala Blue 10rs", cat: "Snacks", wp: 108, rp: 108, unit: "pc" },
  { name: "Kurkure Masala Munch 10rs", cat: "Snacks", wp: 108, rp: 108, unit: "pc" },
  { name: "MDH Super Hing 130rs", cat: "Masala", wp: 104, rp: 104, unit: "pc" },
  { name: "Veeta Premium Toast Rusk", cat: "Snacks", wp: 300, rp: 300, unit: "box" },
  { name: "Lux Soap Set 130rs", cat: "Household", wp: 120, rp: 125, unit: "set" },
  { name: "AAA Pencil Battery Cells", cat: "Stationery", wp: 140, rp: 140, unit: "box" },
  { name: "Four-9 Refined Oil 500ml", cat: "Kirana", wp: 80.67, rp: 81, unit: "pc" },
  { name: "Til Ka Tel 200g", cat: "Kirana", wp: 32, rp: 32, unit: "pc" },
  { name: "Tata Gold Tea 250gm", cat: "Kirana", wp: 160, rp: 160, unit: "pc" },
  { name: "Pears Pure & Gentle Soap 156rs", cat: "Household", wp: 152, rp: 152, unit: "set" },
  { name: "Pass Pass Mouth Freshener 1rs", cat: "Household", wp: 85, rp: 85, unit: "box" },
  { name: "Sabji Masala 100g", cat: "Masala", wp: 60, rp: 60, unit: "pc" },
  { name: "Pili Sarso Yellow Mustard", cat: "Kirana", wp: 120, rp: 120, unit: "kg" },
  { name: "Disposable Chai Glass Cups", cat: "Stationery", wp: 17, rp: 20, unit: "pkt" },
  { name: "Sunsilk Shampoo Bottle 392rs", cat: "Household", wp: 340, rp: 340, unit: "pc" },
  { name: "Nescafe Coffee 24gm", cat: "Kirana", wp: 110, rp: 110, unit: "pc" },
  { name: "Barik Besan Delhi Loose", cat: "Rice & Atta", wp: 78.29, rp: 78.29, unit: "kg" },
  { name: "Hit Mosquito Red Spray 400ml", cat: "Household", wp: 210, rp: 210, unit: "pc" },
  { name: "Yippee Noodles 15rs", cat: "Snacks", wp: 8, rp: 8, unit: "pc" },
  { name: "Four-9 Refined Oil 2L", cat: "Kirana", wp: 316, rp: 316, unit: "pc" },
  { name: "Chana Bhuni Dal Roasted", cat: "Kirana", wp: 130, rp: 130, unit: "kg" },
  { name: "Mota Chola Kabuli Chana", cat: "Kirana", wp: 100, rp: 120, unit: "kg" },
  { name: "Gel Pen Black", cat: "Stationery", wp: 20, rp: 20, unit: "pc" },
  { name: "Chana Dal Namkeen 10rs", cat: "Snacks", wp: 100, rp: 100, unit: "pc" },
  { name: "Agarbatti Incense 50rs", cat: "Household", wp: 240, rp: 240, unit: "pkt" },
  { name: "Madhav Dubar Basmati Rice 30kg", cat: "Rice & Atta", wp: 1140, rp: 1140, unit: "kg" },
  { name: "Cadbury 5 Star 5rs", cat: "Snacks", wp: 245, rp: 245, unit: "box" },
  { name: "Pass Pass Pulse Candy Jar", cat: "Snacks", wp: 145, rp: 145, unit: "jar" },
  { name: "Bandhani Hing 100gm", cat: "Masala", wp: 232, rp: 260, unit: "pc" },
  { name: "Mahadev Matar Namkeen", cat: "Kirana", wp: 370, rp: 380, unit: "pc" },
  { name: "Hit Red Mosquito Spray 320ml", cat: "Household", wp: 190, rp: 190, unit: "pc" },
  { name: "Urad Chilka Dal Split", cat: "Kirana", wp: 98, rp: 105, unit: "kg" },
  { name: "Chaini Khaini Tobacco", cat: "Tobacco", wp: 350, rp: 350, unit: "box" },
  { name: "Milkfood Pure Desi Ghee 500gm", cat: "Kirana", wp: 540, rp: 540, unit: "pc" },
  { name: "Fortune Soap Set (5 Pcs)", cat: "Household", wp: 75, rp: 75, unit: "set" },
  { name: "Haldi Powder No.1 500g", cat: "Masala", wp: 200, rp: 200, unit: "pc" },
  { name: "Rajdhani Dalia Wheat 500gm", cat: "Masala", wp: 28, rp: 35, unit: "pc" },
  { name: "Elaichi Dana Green Cardamom 500g", cat: "Masala", wp: 3200, rp: 3200, unit: "g" },
  { name: "Haldi Powder 10rs", cat: "Masala", wp: 200, rp: 200, unit: "box" },
  { name: "Green Chilli Sauce 1L", cat: "Kirana", wp: 65, rp: 65, unit: "pc" },
  { name: "Ezee Detergent Pouch 10rs", cat: "Household", wp: 108, rp: 108, unit: "box" },
  { name: "Sabut Aamchur Dry Mango", cat: "Kirana", wp: 220, rp: 220, unit: "kg" },
  { name: "Sabudana Sago 250gm", cat: "Kirana", wp: 24, rp: 24, unit: "pc" },
  { name: "Badam Almonds Giri", cat: "Kirana", wp: 1080, rp: 1080, unit: "kg" },
  { name: "Parle Krackjack Biscuits 10rs", cat: "Snacks", wp: 108, rp: 108, unit: "pc" },
  { name: "Dalda Vanaspati 100ml", cat: "Kirana", wp: 17, rp: 17, unit: "pc" },
  { name: "Krackjack Butter Masala 10rs", cat: "Snacks", wp: 108, rp: 108, unit: "pc" },
  { name: "Methi Dana Fenugreek Seeds", cat: "Masala", wp: 100, rp: 100, unit: "kg" },
  { name: "Notebook 3-in-1 Ruled", cat: "Stationery", wp: 180, rp: 180, unit: "pkt" },
  { name: "Hing Powder 50gm", cat: "Masala", wp: 120, rp: 130, unit: "pc" },
  { name: "Cadbury Dairy Milk Silk 125rs", cat: "Snacks", wp: 1000, rp: 1000, unit: "box" },
  { name: "Chilli Lemon Namkeen 10rs", cat: "Snacks", wp: 108, rp: 115, unit: "pc" },
  { name: "Horlicks Chocolate 500gm", cat: "Kirana", wp: 210, rp: 210, unit: "pc" },
  { name: "Rajdhani Semolina Seviyan", cat: "Kirana", wp: 15, rp: 15, unit: "pc" },
  { name: "Khajur Dates 500g", cat: "Kirana", wp: 120, rp: 130, unit: "pc" },
  { name: "Batasa Sugar Drops 10kg", cat: "Kirana", wp: 780, rp: 780, unit: "kg" },
  { name: "Urad Dal Black Whole", cat: "Kirana", wp: 135, rp: 135, unit: "kg" },
  { name: "Jeera Cumin 50gm", cat: "Masala", wp: 16, rp: 16, unit: "pc" },
  { name: "Nawab Basmati Rice", cat: "Rice & Atta", wp: 42.31, rp: 42.31, unit: "kg" },
  { name: "Haridarshan Dhoop 20rs", cat: "Household", wp: 450, rp: 460, unit: "box" },
  { name: "Gup Shup Namkeen 10rs", cat: "Snacks", wp: 100, rp: 100, unit: "pc" },
  { name: "Moong Dal 60rs Pkt", cat: "Kirana", wp: 51, rp: 51, unit: "pc" },
  { name: "Surf Excel Bar 135rs Pack", cat: "Household", wp: 122, rp: 122, unit: "set" },
  { name: "Sabji Masala 5rs Sachet", cat: "Masala", wp: 80, rp: 90, unit: "box" },
  { name: "Haldi Turmeric 1kg", cat: "Masala", wp: 260, rp: 270, unit: "kg" },
  { name: "Good Knight Mosquito Machine Set", cat: "Household", wp: 95, rp: 95, unit: "set" },
  { name: "Lays Classic Salted Yellow 20rs", cat: "Snacks", wp: 17.5, rp: 17.5, unit: "pc" },
  { name: "Akhrot Walnut Giri 250gm", cat: "Kirana", wp: 270, rp: 320, unit: "g" },
  { name: "Wilkinson Shaving Blades", cat: "Household", wp: 220, rp: 220, unit: "box" },
  { name: "Pista Mota Jumbo Pistachio", cat: "Kirana", wp: 3200, rp: 3200, unit: "kg" },
  { name: "Plastic Playing Cards Tash", cat: "Stationery", wp: 480, rp: 480, unit: "box" },
  { name: "Coca-Cola 300ml Can", cat: "Drinks", wp: 31.67, rp: 31.67, unit: "can" },
  { name: "Tops Tomato Sauce 23rs", cat: "Kirana", wp: 15, rp: 15, unit: "pc" },
  { name: "Tomato Sauce 200g Bottle", cat: "Kirana", wp: 28, rp: 28, unit: "pc" },
  { name: "Red Chilli Mirch 50g", cat: "Masala", wp: 17, rp: 17, unit: "pc" },
  { name: "Cherry Shoe Polish Liquid 75ml", cat: "Household", wp: 120, rp: 120, unit: "pc" },
  { name: "Bisleri Mineral Water 200ml", cat: "Drinks", wp: 5, rp: 5, unit: "pc" },
  { name: "Amul Pure Ghee 1kg", cat: "Kirana", wp: 635, rp: 635, unit: "kg" },
  { name: "Shiv Bidi 20rs Bundle", cat: "Tobacco", wp: 380, rp: 380, unit: "pkt" },
  { name: "Down Free Sanitary Pads 105rs", cat: "Household", wp: 70, rp: 70, unit: "pc" },
  { name: "Johnson Baby Oil 40ml", cat: "Household", wp: 63, rp: 63, unit: "pc" },
  { name: "Sendha Namak Rock Salt 200g", cat: "Kirana", wp: 7, rp: 7, unit: "pc" },
  { name: "Maggi 2-Minute Noodles 30rs", cat: "Snacks", wp: 27, rp: 27, unit: "pc" },
  { name: "Cadbury Dairy Milk Lolly/Ball 5rs", cat: "Snacks", wp: 210, rp: 210, unit: "box" },
  { name: "Chana Masala 100g", cat: "Masala", wp: 80, rp: 80, unit: "pc" },
  { name: "Exo Dishwash Bar 10rs", cat: "Household", wp: 8, rp: 8, unit: "pc" },
  { name: "Navratan Namkeen 200gm 50rs", cat: "Snacks", wp: 43, rp: 43, unit: "pc" },
  { name: "Rin Detergent Bar 10rs", cat: "Household", wp: 9, rp: 9, unit: "pc" },
  { name: "Bourbon Biscuits 10rs", cat: "Snacks", wp: 108, rp: 108, unit: "pc" },
  { name: "Ponds Face Wash 50ml", cat: "Household", wp: 100, rp: 100, unit: "pc" },
  { name: "Vim Liquid Gel 130rs", cat: "Household", wp: 115, rp: 120, unit: "pc" },
  { name: "Britannia NutriChoice 20rs", cat: "Snacks", wp: 16, rp: 16, unit: "pc" },
  { name: "Navratan Mixture 10rs", cat: "Snacks", wp: 100, rp: 100, unit: "pc" },
  { name: "Lifebuoy Soap 10rs", cat: "Household", wp: 9, rp: 9, unit: "pc" },
  { name: "Tops Tomato Sauce 1kg", cat: "Kirana", wp: 60, rp: 60, unit: "kg" },
  { name: "Rajma Chitra Rajdhani 500gm", cat: "Kirana", wp: 79, rp: 79, unit: "pc" },
  { name: "Bajaj Almond Drops 89rs", cat: "Household", wp: 81, rp: 81, unit: "pc" },
  { name: "Arhar Toor Dal 2 No.", cat: "Kirana", wp: 98, rp: 98, unit: "kg" },
  { name: "Semi Vermicelli 10rs", cat: "Kirana", wp: 750, rp: 750, unit: "box" },
  { name: "Nescafe Classic Coffee Pouch 10rs", cat: "Kirana", wp: 648, rp: 648, unit: "box" },
  { name: "Raag Gold Vanaspati Tin 15L", cat: "Kirana", wp: 2530, rp: 2530, unit: "tin" },
  { name: "Krishn Desi Ghee 1kg Jar", cat: "Kirana", wp: 550, rp: 550, unit: "kg" },
  { name: "MDH Degi Mirch 100g", cat: "Masala", wp: 100, rp: 100, unit: "pc" },
  { name: "Red Label Tea 260rs", cat: "Kirana", wp: 234, rp: 234, unit: "pc" },
  { name: "Party Green Basmati Rice 30kg", cat: "Rice & Atta", wp: 1510, rp: 1510, unit: "kg" },
  { name: "Sabudana Sago 500g", cat: "Kirana", wp: 48, rp: 48, unit: "pc" },
  { name: "Santoor Beauty Soap Set", cat: "Household", wp: 130, rp: 130, unit: "set" },
  { name: "Thums Up 2L Bottle", cat: "Drinks", wp: 680, rp: 680, unit: "box" },
  { name: "Mix Pickle Achar 1kg", cat: "Kirana", wp: 130, rp: 130, unit: "kg" },
  { name: "Funtop Tomato Sauce 5L Can", cat: "Kirana", wp: 250, rp: 250, unit: "can" },
  { name: "Real Mixed Fruit Juice 30rs", cat: "Drinks", wp: 600, rp: 600, unit: "box" },
  { name: "Parachute Coconut Oil 100ml", cat: "Household", wp: 64, rp: 64, unit: "pc" },
  { name: "Black Salt Kala Namak 200g", cat: "Kirana", wp: 10, rp: 12, unit: "pc" },
  { name: "Nutrifresh Chakki Atta 5kg", cat: "Rice & Atta", wp: 1700, rp: 1700, unit: "kg" },
  { name: "Ujala Supreme Fabric Whitener", cat: "Household", wp: 34, rp: 34, unit: "pc" },
  { name: "Duet Toffee Jar", cat: "Snacks", wp: 135, rp: 135, unit: "jar" },
  { name: "Matar Green Peas Namkeen 10rs", cat: "Snacks", wp: 100, rp: 100, unit: "pc" },
  { name: "Rajshree Pan Masala 10rs", cat: "Tobacco", wp: 200, rp: 210, unit: "box" },
  { name: "Fena Washing Powder 10rs", cat: "Household", wp: 7.25, rp: 8.75, unit: "pc" },
  { name: "Kasturi Methi 25g", cat: "Masala", wp: 24, rp: 24, unit: "pc" },
  { name: "Javitri Mace Whole 500gm", cat: "Masala", wp: 1200, rp: 1200, unit: "g" },
  { name: "Crax Rings Tangy Tomato 11gm", cat: "Snacks", wp: 4, rp: 4.5, unit: "pc" },
  { name: "Thums Up 250ml Can/Bottle", cat: "Drinks", wp: 500, rp: 500, unit: "box" },
  { name: "Red Label Tea 160rs", cat: "Kirana", wp: 145, rp: 145, unit: "pc" },
  { name: "Dettol Soap Set 182rs", cat: "Household", wp: 165, rp: 165, unit: "set" },
  { name: "Fresh Mint Candy Jar", cat: "Snacks", wp: 205, rp: 205, unit: "jar" },
  { name: "Fortune Refined Soyabean Oil 1L", cat: "Kirana", wp: 141, rp: 145, unit: "l" },
  { name: "Radhe Krishn Ghee 5kg Tin", cat: "Kirana", wp: 1800, rp: 1800, unit: "tin" },
  { name: "Malka Dal Orange Lentils", cat: "Kirana", wp: 95, rp: 98, unit: "kg" },
  { name: "Tata Salt 1kg Pkt", cat: "Kirana", wp: 28, rp: 28, unit: "kg" },
  { name: "Nestle Munch 10rs", cat: "Snacks", wp: 220, rp: 220, unit: "box" },
  { name: "Refined Soyabean Oil 500ml", cat: "Kirana", wp: 72, rp: 72, unit: "pc" },
  { name: "Maaza Mango Drink 500ml", cat: "Drinks", wp: 31.25, rp: 31.25, unit: "pc" },
  { name: "Rooh Afza Sharbat 1L", cat: "Drinks", wp: 150, rp: 150, unit: "pc" },
  { name: "Dabur Honey 500gm", cat: "Kirana", wp: 220, rp: 220, unit: "pc" },
  { name: "Cycle Pure Agarbatti 10rs", cat: "Household", wp: 100, rp: 100, unit: "box" },
  { name: "Dalchini Cinnamon Sticks", cat: "Masala", wp: 290, rp: 320, unit: "kg" },
  { name: "Vaseline Deep Moisture Cream 30rs", cat: "Household", wp: 22, rp: 25, unit: "pc" },
  { name: "Gillette Guard Razor", cat: "Household", wp: 223, rp: 223, unit: "box" },
  { name: "Frooti Mango Drink 1.2L", cat: "Drinks", wp: 61.05, rp: 65, unit: "pc" },
  { name: "Fruit Flavoured Candy Jar", cat: "Snacks", wp: 188, rp: 188, unit: "jar" },
  { name: "Navratna Ayurvedic Hair Oil 200ml", cat: "Household", wp: 140, rp: 140, unit: "pc" },
  { name: "Ezee Liquid Detergent 199rs", cat: "Household", wp: 180, rp: 180, unit: "pc" },
  { name: "Parle Monaco Biscuits 10rs", cat: "Snacks", wp: 108, rp: 108, unit: "pc" },
  { name: "Close Up Red Hot 300gm", cat: "Household", wp: 230, rp: 230, unit: "pc" },
  { name: "Rajma Chitra Kidney Beans 500gm", cat: "Kirana", wp: 70, rp: 70, unit: "pc" },
  { name: "Soyabean Moti Chunks", cat: "Kirana", wp: 95, rp: 95, unit: "kg" },
  { name: "Ezee Detergent Pouch 5rs", cat: "Household", wp: 55, rp: 60, unit: "box" },
  { name: "Makhana Phool Foxnuts 100g", cat: "Kirana", wp: 110, rp: 110, unit: "pc" },
  { name: "Nescafe Coffee Pouch 10rs", cat: "Kirana", wp: 108, rp: 108, unit: "box" },
  { name: "Cherry Shoe Polish Wax 54rs", cat: "Household", wp: 49, rp: 49, unit: "pc" },
  { name: "Patanjali Dant Kanti 10rs", cat: "Household", wp: 105, rp: 105, unit: "box" },
  { name: "Fogg Body Spray Deo 120ml", cat: "Household", wp: 150, rp: 180, unit: "pc" },
  { name: "Mitha Soda Baking Soda", cat: "Kirana", wp: 60, rp: 60, unit: "kg" },
  { name: "Rajma Chitra Beans Loose", cat: "Kirana", wp: 120, rp: 125, unit: "kg" },
  { name: "Tata Tea Premium 1kg", cat: "Kirana", wp: 430, rp: 430, unit: "kg" },
  { name: "Red Chilli Powder 100gm", cat: "Masala", wp: 34, rp: 34, unit: "pc" },
  { name: "Jeera Cumin Seeds Loose", cat: "Masala", wp: 320, rp: 340, unit: "kg" },
  { name: "Fortune Premium Sugar 5kg", cat: "Rice & Atta", wp: 68, rp: 68, unit: "kg" },
  { name: "Coca-Cola 750ml Bottle", cat: "Drinks", wp: 24, rp: 24, unit: "pc" },
  { name: "Garam Masala Powder 100g", cat: "Masala", wp: 92, rp: 92, unit: "pc" },
  { name: "Pulse Tangy Candy Big Jar", cat: "Snacks", wp: 420, rp: 420, unit: "jar" },
  { name: "MDH Garam Masala 50g", cat: "Masala", wp: 48, rp: 48, unit: "pc" },
  { name: "Funtop Tomato Sauce 5L", cat: "Kirana", wp: 250, rp: 250, unit: "can" },
  { name: "Johnson Baby Soap 25g", cat: "Household", wp: 18, rp: 18, unit: "pc" },
  { name: "Garam Masala Powder 1kg", cat: "Masala", wp: 310, rp: 310, unit: "kg" },
  { name: "Kaju 4 Tukda Cashews", cat: "Kirana", wp: 780, rp: 780, unit: "kg" },
  { name: "Neha Mehendi Cone Pouch", cat: "Household", wp: 50, rp: 50, unit: "box" },
  { name: "Anar Dana Pomegranate Seeds", cat: "Masala", wp: 280, rp: 280, unit: "kg" },
  { name: "Kamla Pasand Pan Masala", cat: "Tobacco", wp: 185, rp: 190, unit: "box" },
  { name: "Happy-Happy Biscuits 5rs", cat: "Snacks", wp: 52.5, rp: 55, unit: "box" },
  { name: "Gutir Basmati Rice 5kg", cat: "Rice & Atta", wp: 550, rp: 550, unit: "kg" },
  { name: "Diet Coke 500ml Can", cat: "Drinks", wp: 1000, rp: 1000, unit: "box" },
  { name: "Dabur Amla Hair Oil 20rs", cat: "Household", wp: 17.5, rp: 17.5, unit: "pc" },
  { name: "Khatta Meetha Namkeen 10rs", cat: "Snacks", wp: 100, rp: 100, unit: "pc" },
  { name: "Funtop Green Chilli Sauce 5L", cat: "Kirana", wp: 250, rp: 250, unit: "can" },
  { name: "Thums Up 20rs Can/Bottle", cat: "Drinks", wp: 490, rp: 490, unit: "box" },
  { name: "Shikhar Pan Masala 10rs", cat: "Tobacco", wp: 130, rp: 130, unit: "box" },
  { name: "Bajaj Almond Drops 1rs Sachet", cat: "Household", wp: 85, rp: 85, unit: "box" },
  { name: "Lahori Jeera Soda 10rs", cat: "Drinks", wp: 8.12, rp: 8.12, unit: "pc" },
  { name: "Pampers Baby Diapers 30rs", cat: "Household", wp: 200, rp: 200, unit: "pc" },
  { name: "Vim Dishwash Bar Set 40rs", cat: "Household", wp: 36, rp: 36, unit: "set" },
  { name: "Akhrot Giri Walnut Kernels", cat: "Kirana", wp: 1200, rp: 1200, unit: "kg" },
  { name: "Flour Mill Atta 44kg Bag", cat: "Rice & Atta", wp: 32.27, rp: 32.27, unit: "kg" },
  { name: "Parle 20-20 Cashew Biscuits 5rs", cat: "Snacks", wp: 52.5, rp: 54, unit: "box" },
  { name: "Bourbon Biscuits 20 Pcs Pack", cat: "Snacks", wp: 180, rp: 180, unit: "box" },
  { name: "Lux Body Wash Soap Set 330rs", cat: "Household", wp: 280, rp: 300, unit: "set" },
  { name: "Godrej Magic Handwash 46rs", cat: "Household", wp: 40, rp: 40, unit: "pc" },
  { name: "Campa Cola Can 250ml", cat: "Drinks", wp: 600, rp: 600, unit: "box" },
  { name: "Coca-Cola 250ml Bottle", cat: "Drinks", wp: 500, rp: 500, unit: "box" },
  { name: "Dabur Red Toothpaste 10rs", cat: "Household", wp: 8.75, rp: 8.75, unit: "pc" },
  { name: "Soya Sauce 750ml Bottle", cat: "Kirana", wp: 70, rp: 70, unit: "pc" },
  { name: "Nescafe Classic Coffee 45g", cat: "Kirana", wp: 240, rp: 240, unit: "pc" },
  { name: "Tata Agni Leaf Tea 250gm", cat: "Kirana", wp: 48, rp: 48, unit: "pc" },
  { name: "Red Chilli Mirch Powder No.1 1kg", cat: "Masala", wp: 300, rp: 350, unit: "kg" },
  { name: "Salted Pistachios Pista", cat: "Kirana", wp: 3600, rp: 3600, unit: "kg" },
  { name: "Kurkure Puffcorn Yummy Cheese 5rs", cat: "Snacks", wp: 54, rp: 54, unit: "pc" },
  { name: "Parle Mango Bite Candy Pouch 50rs", cat: "Snacks", wp: 40, rp: 40, unit: "pkt" },
  { name: "Uncle Chips Spicy Treat 10rs", cat: "Snacks", wp: 108, rp: 108, unit: "pc" },
  { name: "Pears Transparent Soap 20rs", cat: "Household", wp: 18, rp: 18, unit: "pc" },
  { name: "Odomos Mosquito Cream 30rs", cat: "Household", wp: 25, rp: 25, unit: "pc" },
  { name: "Paneer Masala 10rs", cat: "Masala", wp: 80, rp: 80, unit: "box" },
  { name: "Red Chilli Sauce 500ml", cat: "Kirana", wp: 70, rp: 70, unit: "pc" },
  { name: "Party Green Basmati Rice 26kg", cat: "Rice & Atta", wp: 46.15, rp: 46.15, unit: "kg" },
  { name: "Patanjali Sharbat Gulab 1L", cat: "Drinks", wp: 95, rp: 150, unit: "pc" },
  { name: "Today CTC Tea 250g", cat: "Kirana", wp: 110, rp: 110, unit: "pc" },
  { name: "Melody Chocolaty Toffees Big Jar", cat: "Snacks", wp: 720, rp: 720, unit: "jar" },
  { name: "Limca Lemon Drink 250ml", cat: "Drinks", wp: 16.33, rp: 16.33, unit: "pc" },
  { name: "Pista Namkeen Khula Roasted", cat: "Kirana", wp: 1600, rp: 1600, unit: "kg" },
  { name: "Ezee Liquid Detergent 225rs", cat: "Household", wp: 200, rp: 200, unit: "pc" },
  { name: "Fortune Kachi Ghani Mustard Oil 1L", cat: "Kirana", wp: 188.5, rp: 190, unit: "l" },
  { name: "Parle Monaco Salted Biscuits 5rs", cat: "Snacks", wp: 90, rp: 90, unit: "box" },
  { name: "Godrej Night Bulb 10rs", cat: "Household", wp: 220, rp: 220, unit: "box" },
  { name: "Reetha Soapnuts Whole", cat: "Kirana", wp: 150, rp: 150, unit: "kg" },
  { name: "Rajdhani Besan Gram Flour Loose", cat: "Rice & Atta", wp: 85, rp: 88, unit: "kg" },
  { name: "Chana Dal 5rs Pkt", cat: "Snacks", wp: 52, rp: 52, unit: "pc" },
  { name: "Neeraj Mehendi Powder 250g", cat: "Household", wp: 96, rp: 96, unit: "pc" },
  { name: "Mosquito Coil Agarbatti", cat: "Household", wp: 70, rp: 70, unit: "box" },
  { name: "Fanta Orange Drink 750ml", cat: "Drinks", wp: 750, rp: 750, unit: "box" },
  { name: "Barik Sooji Fine Semolina", cat: "Rice & Atta", wp: 36, rp: 36, unit: "kg" },
  { name: "Aloo Bhujia Namkeen 5rs", cat: "Snacks", wp: 52, rp: 52, unit: "pc" },
  { name: "Bournvita Health Drink 1kg", cat: "Kirana", wp: 435, rp: 450, unit: "kg" },
  { name: "Pears Pure & Gentle Soap 35rs", cat: "Household", wp: 32, rp: 32, unit: "pc" },
  { name: "Kaju Sabut Whole Cashew W240", cat: "Kirana", wp: 950, rp: 1020, unit: "kg" },
  { name: "Parachute 100% Coconut Oil 500ml", cat: "Household", wp: 300, rp: 300, unit: "pc" },
  { name: "Bisleri Mineral Water 2L", cat: "Drinks", wp: 22.22, rp: 22.22, unit: "pc" },
  { name: "Lays Tomato Tango Red 25rs", cat: "Snacks", wp: 17.5, rp: 18, unit: "pc" },
  { name: "Tide Plus Extra Power Detergent 10rs", cat: "Household", wp: 9, rp: 9, unit: "pc" },
  { name: "Pepsodent Germi Check 100gm", cat: "Household", wp: 75, rp: 75, unit: "pc" },
  { name: "Dal Chawal Namkeen 5rs", cat: "Snacks", wp: 60, rp: 60, unit: "box" },
  { name: "MDH Dahi Vada Raita Masala", cat: "Masala", wp: 92, rp: 92, unit: "pc" },
  { name: "Aashirvaad Superior MP Atta 5kg", cat: "Rice & Atta", wp: 1368, rp: 1370, unit: "kg" },
  { name: "Double Chabi Basmati Rice", cat: "Rice & Atta", wp: 106, rp: 110, unit: "kg" },
  { name: "Odomos Mosquito Repellent 105rs", cat: "Household", wp: 95, rp: 95, unit: "pc" },
  { name: "MDH Haldi Powder 100g", cat: "Masala", wp: 40, rp: 40, unit: "pc" },
  { name: "Fair & Handsome Cream 10rs Sachet", cat: "Household", wp: 110, rp: 110, unit: "box" },
  { name: "Navratna Cool Hair Oil 90rs", cat: "Household", wp: 80, rp: 85, unit: "pc" },
  { name: "Dabur Pure Honey 100gm", cat: "Kirana", wp: 73, rp: 76, unit: "pc" },
  { name: "Godrej Expert Hair Dye 15rs", cat: "Household", wp: 130, rp: 130, unit: "box" },
  { name: "Kissan Fresh Tomato Ketchup 10rs", cat: "Kirana", wp: 8.5, rp: 8.5, unit: "pc" },
  { name: "Cycle Agarbatti 20rs Pack", cat: "Household", wp: 200, rp: 200, unit: "box" },
  { name: "Polythene Panni 5kg Pkt", cat: "Stationery", wp: 130, rp: 130, unit: "pkt" },
  { name: "Crax Curls Chatpata Masala", cat: "Snacks", wp: 4.5, rp: 4.8, unit: "pc" },
  { name: "Steel Juna Scrubber", cat: "Household", wp: 90, rp: 90, unit: "box" },
  { name: "Britannia Good Day Cashew 10rs", cat: "Snacks", wp: 102.85, rp: 105, unit: "pc" },
  { name: "Britannia 50-50 Sweet & Salty 5rs", cat: "Snacks", wp: 54, rp: 54, unit: "box" },
  { name: "Dabur 100% Pure Honey 1kg", cat: "Kirana", wp: 430, rp: 430, unit: "kg" },
  { name: "Harpic Power Plus 46rs", cat: "Household", wp: 40, rp: 42, unit: "pc" },
  { name: "Gillette Guard Shaving Blades Box", cat: "Household", wp: 120, rp: 120, unit: "box" },
  { name: "Head & Shoulders Shampoo 2rs", cat: "Household", wp: 26, rp: 26, unit: "box" },
  { name: "Navratna Cool Talc Powder 105rs", cat: "Household", wp: 95, rp: 95, unit: "pc" },
  { name: "Red Chilli Mirch Powder No.1 500g", cat: "Masala", wp: 260, rp: 260, unit: "pc" },
  { name: "Dove Nourishing Body Soap 93rs", cat: "Household", wp: 84, rp: 84, unit: "pc" },
  { name: "Bread Crumbs Panko 500g", cat: "Kirana", wp: 140, rp: 140, unit: "pc" },
  { name: "Funtoosh Mouth Freshener 50rs", cat: "Snacks", wp: 40, rp: 40, unit: "box" },
  { name: "Dhaniya Powder KBM 100g", cat: "Masala", wp: 30, rp: 30, unit: "pc" },
  { name: "Pears Soap Set (4 Pcs)", cat: "Household", wp: 145, rp: 145, unit: "set" },
  { name: "Urad Dhuli Washed White Dal", cat: "Kirana", wp: 130, rp: 130, unit: "kg" },
  { name: "Cinthol Confidence Soap 10rs", cat: "Household", wp: 8.75, rp: 8.75, unit: "pc" },
  { name: "Dettol Liquid Handwash Refill 650ml", cat: "Household", wp: 92, rp: 92, unit: "pc" },
  { name: "Good Knight Power Activ+ Refill", cat: "Household", wp: 80, rp: 80, unit: "pc" },
  { name: "Godrej Magic Handwash Sachet 10rs", cat: "Household", wp: 90, rp: 90, unit: "box" },
  { name: "Parle Dark Fantasy Biscuits 10rs", cat: "Snacks", wp: 100, rp: 100, unit: "pc" },
  { name: "Local Mineral Water 500ml", cat: "Drinks", wp: 120, rp: 120, unit: "box" },
  { name: "Sunsilk Black Shine Shampoo 175rs", cat: "Household", wp: 160, rp: 160, unit: "pc" },
  { name: "Phool Jhadu Grass Broom", cat: "Household", wp: 67, rp: 75, unit: "pc" },
  { name: "Nestle KitKat Chocolate 20rs", cat: "Snacks", wp: 540, rp: 540, unit: "box" },
  { name: "Cadbury Dairy Milk Crispello 10rs", cat: "Snacks", wp: 360, rp: 360, unit: "box" },
  { name: "Hit Cockroach Spray Black 125rs", cat: "Household", wp: 115, rp: 115, unit: "pc" },
  { name: "Sting Energy Drink 20rs Bottle", cat: "Drinks", wp: 520, rp: 520, unit: "box" },
  { name: "Lays Classic Salted 25rs", cat: "Snacks", wp: 17.5, rp: 17.5, unit: "pc" },
  { name: "Fair & Lovely Face Cream 50gm", cat: "Household", wp: 124, rp: 124, unit: "pc" },
  { name: "Jawa Vermicelli 400g Pkt", cat: "Kirana", wp: 50, rp: 50, unit: "pc" },
  { name: "Arhar Toor Dal Premium 1 No.", cat: "Kirana", wp: 118, rp: 120, unit: "kg" },
  { name: "Soyabean Choti Mini Chunks", cat: "Kirana", wp: 100, rp: 100, unit: "kg" },
  { name: "Britannia Jim Jam Biscuits 10rs", cat: "Snacks", wp: 9, rp: 9, unit: "pc" },
  { name: "Sugar Premium Chini 5kg", cat: "Rice & Atta", wp: 340, rp: 340, unit: "kg" },
  { name: "Kasturi Methi Dry Fenugreek 500g", cat: "Masala", wp: 120, rp: 120, unit: "g" },
  { name: "Red Chilli Sauce 5L Can", cat: "Kirana", wp: 250, rp: 250, unit: "can" },
  { name: "Fair & Lovely Face Cream 25g", cat: "Household", wp: 65, rp: 65, unit: "pc" },
  { name: "Sarvodaya Chakki Atta 5kg", cat: "Rice & Atta", wp: 161, rp: 161, unit: "kg" },
  { name: "Raag Vanaspati Oil Pouch 1L", cat: "Kirana", wp: 134, rp: 134, unit: "l" },
  { name: "Johnson Baby Soap 70rs", cat: "Household", wp: 65, rp: 65, unit: "pc" },
  { name: "Cadbury 5 Star Chocolate 10rs", cat: "Snacks", wp: 360, rp: 360, unit: "box" },
  { name: "Fanta Orange Drink 2L Bottle", cat: "Drinks", wp: 75.56, rp: 75.56, unit: "pc" },
  { name: "Maggi 4-Pack Family 60rs", cat: "Snacks", wp: 54, rp: 56, unit: "pc" },
  { name: "MDH Chunky Chat Masala 100g", cat: "Masala", wp: 80, rp: 80, unit: "pc" },
  { name: "Polythene Panni 2kg Pkt", cat: "Stationery", wp: 130, rp: 130, unit: "pkt" },
  { name: "Parachute Coconut Hair Oil 20rs", cat: "Household", wp: 17.5, rp: 17.5, unit: "pc" },
  { name: "Lux Velvet Touch Soap 10rs", cat: "Household", wp: 36, rp: 38, unit: "box" },
  { name: "Sabut Dry Mango Aamchur Whole", cat: "Kirana", wp: 220, rp: 220, unit: "kg" },
  { name: "Goldiee Biryani Masala 10rs", cat: "Masala", wp: 8, rp: 8, unit: "pc" },
  { name: "Coca-Cola 1L Bottle", cat: "Drinks", wp: 42, rp: 42, unit: "pc" },
  { name: "Gulabari Pure Rose Water 52rs", cat: "Household", wp: 47, rp: 47, unit: "pc" },
  { name: "Pamper Baby Diaper 10rs Sachet", cat: "Household", wp: 80, rp: 80, unit: "box" },
  { name: "Hit Rat Glue Pad Trap 100rs", cat: "Household", wp: 50, rp: 50, unit: "pc" },
  { name: "Fena Detergent Powder 5rs Sachet", cat: "Household", wp: 4.3, rp: 4.5, unit: "pc" },
  { name: "Punjabi Tadka Namkeen 5rs", cat: "Snacks", wp: 52, rp: 55, unit: "pc" },
  { name: "Ghadi Detergent Powder 10rs", cat: "Household", wp: 8.75, rp: 8.75, unit: "pc" },
  { name: "Rajdhani Fine Sooji 500g", cat: "Rice & Atta", wp: 27, rp: 27, unit: "pc" },
  { name: "Nestle KitKat Chocolate 10rs", cat: "Snacks", wp: 380, rp: 380, unit: "box" },
  { name: "Parle Cream Biscuits 5rs", cat: "Snacks", wp: 50, rp: 50, unit: "pc" },
  { name: "Dermi Cool Prickly Heat Powder 169rs", cat: "Household", wp: 160, rp: 160, unit: "pc" },
  { name: "Whole Green Moong Sabut", cat: "Kirana", wp: 90, rp: 90, unit: "kg" },
  { name: "Red Chilli Mirch Powder 50gm", cat: "Masala", wp: 17, rp: 21, unit: "pc" },
  { name: "Tata Agni Leaf Tea 500gm", cat: "Kirana", wp: 85, rp: 85, unit: "pc" },
  { name: "Chironji Dana 500gm", cat: "Kirana", wp: 78, rp: 78, unit: "g" },
  { name: "Boroplus Antiseptic Cream 40ml", cat: "Household", wp: 82, rp: 82, unit: "pc" },
  { name: "Sketch Pens Set (12 Colours)", cat: "Stationery", wp: 120, rp: 120, unit: "box" },
  { name: "Chana Dal Split Bengal Gram", cat: "Kirana", wp: 78, rp: 78, unit: "kg" },
  { name: "Malai Sev Namkeen 10rs", cat: "Snacks", wp: 100, rp: 100, unit: "pc" },
  { name: "Surf Excel Laundry Soap 135rs", cat: "Household", wp: 122, rp: 122, unit: "set" },
  { name: "Bingo Tedhe Medhe Masala 5rs", cat: "Snacks", wp: 50, rp: 50, unit: "pc" },
  { name: "Rajdhani Chana Dal 500gm", cat: "Kirana", wp: 52, rp: 60, unit: "pc" },
  { name: "Mini Soya Chunks 200g", cat: "Kirana", wp: 40, rp: 40, unit: "pc" },
  { name: "Pencil Sharpener Box", cat: "Stationery", wp: 30, rp: 30, unit: "box" },
  { name: "Aloo Bhujia Namkeen 200gm", cat: "Snacks", wp: 47, rp: 47, unit: "pc" },
  { name: "Imli Seedless Tamarind 200g", cat: "Masala", wp: 30, rp: 30, unit: "pc" },
  { name: "Tata Agni Leaf Tea 1kg", cat: "Kirana", wp: 210, rp: 210, unit: "kg" },
  { name: "Kali Mirch Black Pepper 50gm", cat: "Masala", wp: 74, rp: 74, unit: "pc" },
  { name: "Meetha Soda Baking Soda Loose", cat: "Kirana", wp: 50, rp: 50, unit: "kg" },
  { name: "Kanchi Basmati Rice 26kg", cat: "Rice & Atta", wp: 950, rp: 950, unit: "kg" },
  { name: "Sabut Garam Masala Card Pack 10rs", cat: "Masala", wp: 120, rp: 120, unit: "box" },
  { name: "Champion Rusk Toast Box", cat: "Snacks", wp: 400, rp: 400, unit: "box" },
  { name: "Crax Corn Rings 5rs", cat: "Snacks", wp: 62, rp: 62, unit: "box" },
  { name: "Kala Chana Brown Chickpeas", cat: "Kirana", wp: 85, rp: 90, unit: "kg" },
  { name: "Paper Playing Cards Tash", cat: "Stationery", wp: 150, rp: 150, unit: "box" },
  { name: "Keo Karpin Hair Oil 100ml", cat: "Household", wp: 50, rp: 50, unit: "pc" },
  { name: "Crunchy Namkeen 10rs", cat: "Snacks", wp: 9, rp: 9, unit: "pc" },
  { name: "Gaund Babul Edible Gum", cat: "Kirana", wp: 280, rp: 280, unit: "kg" },
  { name: "Kalonji Nigella Seeds", cat: "Masala", wp: 300, rp: 300, unit: "kg" },
  { name: "Sona Masoori Rice 1st Quality", cat: "Rice & Atta", wp: 1710, rp: 1710, unit: "kg" },
  { name: "MDH Degi Mirch Powder 100g", cat: "Masala", wp: 100, rp: 100, unit: "pc" },
  { name: "Tomato Puree Pouch 1kg", cat: "Kirana", wp: 150, rp: 150, unit: "pc" },
  { name: "Bajaj Almond Drops Hair Oil 2rs", cat: "Household", wp: 85, rp: 85, unit: "box" },
  { name: "Sunsilk Shampoo 145rs Bottle", cat: "Household", wp: 130, rp: 130, unit: "pc" },
  { name: "Pooja Mombatti Candles Box", cat: "Household", wp: 18, rp: 18, unit: "box" },
  { name: "Kartik Dubar Basmati Rice", cat: "Rice & Atta", wp: 1160, rp: 1160, unit: "kg" },
  { name: "Brooke Bond Red Label Tea 135rs", cat: "Kirana", wp: 122, rp: 122, unit: "pc" },
  { name: "Dry Mango Amchur Powder 100gm", cat: "Masala", wp: 72, rp: 72, unit: "pc" },
  { name: "Lays Magic Masala Blue 25rs", cat: "Snacks", wp: 17.5, rp: 17.5, unit: "pc" },
  { name: "Tide Green Lemon Detergent 1kg", cat: "Household", wp: 70, rp: 70, unit: "kg" },
  { name: "Gup Shup Namkeen Mixture 10rs", cat: "Snacks", wp: 100, rp: 100, unit: "pc" },
  { name: "Limca Fresh Lemon 750ml", cat: "Drinks", wp: 750, rp: 750, unit: "box" },
  { name: "Funtop White Synthetic Vinegar", cat: "Kirana", wp: 48, rp: 48, unit: "pc" },
  { name: "Steel Wool Juna Scrubber", cat: "Household", wp: 90, rp: 90, unit: "box" },
  { name: "Parle Bourbon Chocolate Biscuits 10rs", cat: "Snacks", wp: 105, rp: 108, unit: "pc" },
  { name: "Brooke Bond Red Label Tea 1kg", cat: "Kirana", wp: 420, rp: 420, unit: "kg" },
  { name: "Red Chilli Powder Kashmiri", cat: "Masala", wp: 34, rp: 40, unit: "pc" },
  { name: "Vaseline Intensive Care Lotion 400ml", cat: "Household", wp: 360, rp: 360, unit: "pc" },
  { name: "Close Up Red Hot 150gm", cat: "Household", wp: 125, rp: 125, unit: "pc" },
  { name: "Dabur Red Toothpaste 50gm 20rs", cat: "Household", wp: 17.5, rp: 18, unit: "pc" },
  { name: "Local Packaged Drinking Water 2L", cat: "Drinks", wp: 110, rp: 110, unit: "box" },
  { name: "Magic Cream Chocolate Biscuits 9rs", cat: "Snacks", wp: 8.5, rp: 8.33, unit: "pc" },
  { name: "Navratna Cool Talc Powder 55rs", cat: "Household", wp: 50, rp: 50, unit: "pc" },
  { name: "Rajdhani Poha Flattened Rice 500g", cat: "Rice & Atta", wp: 42, rp: 42, unit: "pc" },
  { name: "Garnier Black Natural Hair Colour", cat: "Household", wp: 380, rp: 380, unit: "box" },
  { name: "Kurkure Chilli Chatka 25rs", cat: "Snacks", wp: 17.5, rp: 17.5, unit: "pc" },
  { name: "Dalda Pure Vanaspati 1L Pouch", cat: "Kirana", wp: 160, rp: 160, unit: "l" },
  { name: "Britannia Good Day Butter 5rs", cat: "Snacks", wp: 54, rp: 54, unit: "box" },
  { name: "Good Knight Fast Card 10rs", cat: "Household", wp: 11.25, rp: 11.25, unit: "box" },
  { name: "Maggi 2-Minute Noodles 15rs", cat: "Snacks", wp: 13.5, rp: 13.5, unit: "pc" },
  { name: "Bura Sugar Powder Loose", cat: "Kirana", wp: 68, rp: 68, unit: "kg" },
  { name: "White Gold Basmati Rice 26kg", cat: "Rice & Atta", wp: 880, rp: 880, unit: "kg" },
  { name: "Fortune Kachi Ghani Mustard Oil 500ml", cat: "Kirana", wp: 95.84, rp: 97, unit: "pc" },
  { name: "Fevikwik Instant Adhesive 5rs", cat: "Household", wp: 110, rp: 110, unit: "box" },
  { name: "Parle Toffees Assorted 50rs Pouch", cat: "Snacks", wp: 40, rp: 40, unit: "pkt" },
  { name: "Dhaniya Coriander Powder 500g", cat: "Masala", wp: 130, rp: 130, unit: "pc" },
  { name: "Salted Pistachios 250gm", cat: "Kirana", wp: 375, rp: 375, unit: "g" },
  { name: "Khatta Meetha Namkeen 5rs", cat: "Snacks", wp: 52, rp: 52, unit: "pc" },
  { name: "Palak Sev Crunchy Namkeen 10rs", cat: "Snacks", wp: 100, rp: 100, unit: "pc" },
  { name: "Jaggery Gud Choti Bheli", cat: "Kirana", wp: 75, rp: 80, unit: "kg" },
  { name: "Kashi Dhoop Batti", cat: "Household", wp: 100, rp: 100, unit: "box" },
  { name: "Dalda Vanaspati Tin 15L", cat: "Kirana", wp: 2320, rp: 2320, unit: "tin" },
  { name: "Matchbox Safety Matches 10rs Pack", cat: "Household", wp: 80, rp: 80, unit: "box" },
  { name: "Fena Detergent Powder 4kg", cat: "Household", wp: 350, rp: 355, unit: "kg" },
  { name: "Sugar Chini Loose", cat: "Rice & Atta", wp: 58, rp: 60, unit: "kg" },
  { name: "Chakki Fresh Atta 40kg Bag", cat: "Rice & Atta", wp: 1250, rp: 1250, unit: "kg" },
  { name: "Suraj Bidi Bundle", cat: "Tobacco", wp: 150, rp: 150, unit: "pkt" },
  { name: "Krishn Desi Ghee 200gm", cat: "Kirana", wp: 130, rp: 130, unit: "pc" },
  { name: "Sattu No.1 Roasted Gram Flour 500g", cat: "Rice & Atta", wp: 55, rp: 55, unit: "pc" },
  { name: "Catch Club Soda 300ml Cans", cat: "Drinks", wp: 360, rp: 360, unit: "box" },
  { name: "Colgate Dental Cream 100gm 73rs", cat: "Household", wp: 65, rp: 65, unit: "pc" },
  { name: "Nut Cracker Spicy Peanuts 55rs", cat: "Snacks", wp: 47, rp: 47, unit: "pc" },
  { name: "Fennel Seeds Sauf Green", cat: "Masala", wp: 240, rp: 260, unit: "kg" },
  { name: "Ratol Rat Poison Paste / Book", cat: "Household", wp: 50, rp: 50, unit: "pc" },
  { name: "Red Chilli Mirch Powder No.1 200g", cat: "Masala", wp: 70, rp: 70, unit: "pc" },
  { name: "Sona Masoori Rice 2nd Quality", cat: "Rice & Atta", wp: 1500, rp: 1500, unit: "kg" },
  { name: "Deep Pure Desi Ghee 1L Jar", cat: "Kirana", wp: 160, rp: 160, unit: "l" },
  { name: "Sprite Refreshing Drink 1L Bottle", cat: "Drinks", wp: 630, rp: 630, unit: "box" },
  { name: "Pears Transparent Soap 53rs", cat: "Household", wp: 47, rp: 47, unit: "pc" },
  { name: "Nova Premium Chai Tea 250gm", cat: "Kirana", wp: 83, rp: 83, unit: "pc" },
  { name: "Yakeen Refined Soyabean Oil 1L", cat: "Kirana", wp: 112, rp: 115, unit: "l" },
  { name: "Tomato Sauce 1rs Sachet Box", cat: "Kirana", wp: 50, rp: 50, unit: "box" },
  { name: "Notebook Mathematics Ruled", cat: "Stationery", wp: 180, rp: 180, unit: "pkt" },
  { name: "Notebook Hindi Ruled", cat: "Stationery", wp: 180, rp: 180, unit: "pkt" },
  { name: "Dry Ginger Saunth Powder 500gm", cat: "Masala", wp: 340, rp: 340, unit: "g" },
  { name: "Kuber Khaini 20rs Box", cat: "Tobacco", wp: 270, rp: 270, unit: "box" },
  { name: "Disposable Glasses 500ml", cat: "Stationery", wp: 60, rp: 60, unit: "pkt" },
  { name: "Party Blue Basmati Rice 26kg", cat: "Rice & Atta", wp: 76.92, rp: 76.92, unit: "kg" },
  { name: "Dabur Red Tooth Powder Manjan 38rs", cat: "Household", wp: 35, rp: 35, unit: "pc" },
  { name: "MamyPoko Pants Diapers 10rs", cat: "Household", wp: 80, rp: 90, unit: "box" },
  { name: "502 Pataka Bidi Bundle", cat: "Tobacco", wp: 390, rp: 390, unit: "pkt" },
  { name: "MDH Kashmiri Mirch Powder 500gm", cat: "Masala", wp: 260, rp: 260, unit: "pc" },
  { name: "Moti Sooji Coarse Semolina", cat: "Rice & Atta", wp: 36, rp: 38, unit: "kg" },
  { name: "Bisleri Mineral Water 250ml Bottles", cat: "Drinks", wp: 130, rp: 130, unit: "box" },
  { name: "Dabur Hajmola Regular Jar", cat: "Kirana", wp: 145, rp: 150, unit: "jar" },
  { name: "Patanjali Cow Ghee 1kg 731rs", cat: "Kirana", wp: 680, rp: 680, unit: "kg" },
  { name: "Bhavnagri Gathiya Namkeen 10rs", cat: "Snacks", wp: 100, rp: 100, unit: "pc" },
  { name: "Catch Jeera Masala Drink 10rs", cat: "Drinks", wp: 8.33, rp: 8.33, unit: "pc" },
  { name: "Coca-Cola 2L Bottle", cat: "Drinks", wp: 75.56, rp: 75.56, unit: "pc" },
  { name: "Rolling Paper 5rs Booklet", cat: "Snacks", wp: 70, rp: 70, unit: "pkt" },
  { name: "Vicks VapoRub 45rs", cat: "Household", wp: 41, rp: 41, unit: "pc" },
  { name: "5 Bhai Washing Soap Bar", cat: "Household", wp: 75, rp: 75, unit: "box" },
  { name: "Fanta Orange Drink 300ml Can", cat: "Drinks", wp: 700, rp: 700, unit: "can" },
  { name: "Imli Chutney Candy Jar", cat: "Snacks", wp: 180, rp: 180, unit: "jar" },
  { name: "All Out Mosquito Repellent Refill", cat: "Household", wp: 85, rp: 90, unit: "pc" },
  { name: "Ginger Adrak Lachha Salted", cat: "Kirana", wp: 45, rp: 45, unit: "pc" },
  { name: "Matcha Tea Leaf 200g", cat: "Kirana", wp: 75, rp: 75, unit: "pc" },
  { name: "Tansen Pan Masala Box", cat: "Tobacco", wp: 220, rp: 220, unit: "box" },
  { name: "Anar Dana Powder 250gm", cat: "Masala", wp: 70, rp: 70, unit: "pc" },
  { name: "Ajinomoto Monosodium Glutamate 500gm", cat: "Masala", wp: 90, rp: 90, unit: "pc" },
  { name: "Kali Mirch Whole Black Pepper", cat: "Masala", wp: 800, rp: 800, unit: "kg" },
  { name: "Food Colour Hara Green 100gm", cat: "Kirana", wp: 35, rp: 35, unit: "pc" },
  { name: "MDH Jaljeera Powder 100g", cat: "Masala", wp: 61, rp: 61, unit: "pc" },
  { name: "Tops Instant Noodles 10rs", cat: "Snacks", wp: 7.5, rp: 7.5, unit: "pc" },
  { name: "Surf Excel Detergent 500g", cat: "Household", wp: 67, rp: 67, unit: "pc" },
  { name: "Moong Dhuli Washed Yellow Dal 1 No.", cat: "Kirana", wp: 98, rp: 98, unit: "kg" },
  { name: "MDH Sabji Masala 50g", cat: "Masala", wp: 31, rp: 31, unit: "pc" },
  { name: "Gola Burada Desiccated Coconut", cat: "Kirana", wp: 220, rp: 220, unit: "kg" },
  { name: "Kissan Fresh Tomato Ketchup 500ml", cat: "Kirana", wp: 50, rp: 50, unit: "pc" },
  { name: "Chicken Masala 5rs Sachet", cat: "Masala", wp: 80, rp: 85, unit: "box" },
  { name: "Shikhar Pan Masala 5rs", cat: "Tobacco", wp: 6.29, rp: 6.29, unit: "pc" },
  { name: "Ghadi Detergent Powder 500g", cat: "Household", wp: 33.5, rp: 35, unit: "pc" },
  { name: "Lal Mirch Red Chilli Powder 10rs", cat: "Masala", wp: 200, rp: 200, unit: "box" },
  { name: "MDH Sambar Masala 100g", cat: "Masala", wp: 70, rp: 70, unit: "pc" },
  { name: "Prachin Bidi Bundle", cat: "Tobacco", wp: 150, rp: 150, unit: "pkt" },
  { name: "Hindustan Gold Basmati Rice 26kg", cat: "Rice & Atta", wp: 1200, rp: 1200, unit: "kg" },
  { name: "Nip Dishwash Bar Set 30rs", cat: "Household", wp: 26, rp: 26, unit: "set" },
  { name: "Meat Masala Powder 50g", cat: "Masala", wp: 42, rp: 42, unit: "pc" },
  { name: "Lakshman Rekha Cockroach Chalk Box", cat: "Household", wp: 140, rp: 140, unit: "box" },
  { name: "Tide Plus Detergent Powder 3kg", cat: "Household", wp: 270, rp: 270, unit: "kg" },
  { name: "Chhuara Dry Dates Whole", cat: "Kirana", wp: 220, rp: 220, unit: "kg" },
  { name: "Tops Synthetic Vinegar 610ml", cat: "Kirana", wp: 48, rp: 48, unit: "pc" },
  { name: "Sabut Dhaniya Whole Coriander Seeds", cat: "Masala", wp: 180, rp: 180, unit: "kg" },
  { name: "Soya Sauce 5kg Can", cat: "Kirana", wp: 250, rp: 250, unit: "can" },
  { name: "Kurkure Puffcorn 20rs", cat: "Snacks", wp: 17.5, rp: 17.5, unit: "pc" },
  { name: "Roasted Salted Pista Pkt", cat: "Kirana", wp: 400, rp: 400, unit: "pc" },
  { name: "Bura Sugar 500gm Pkt", cat: "Kirana", wp: 35, rp: 40, unit: "pc" },
  { name: "Veeta Premium Toast Rusk 20rs", cat: "Snacks", wp: 600, rp: 600, unit: "box" },
  { name: "Dove Shampoo 5rs Sachet", cat: "Household", wp: 65, rp: 70, unit: "box" },
  { name: "Seekh Jhadu Coconut Broom", cat: "Household", wp: 42, rp: 42, unit: "pc" },
  { name: "Marlboro Switch Cigarette", cat: "Tobacco", wp: 444, rp: 444, unit: "box" },
  { name: "Kali Mirch Black Pepper 500gm", cat: "Masala", wp: 850, rp: 850, unit: "g" },
  { name: "Pasta Masala Sachet Box", cat: "Masala", wp: 80, rp: 90, unit: "box" },
  { name: "Nataraj Ballpoint Pens", cat: "Stationery", wp: 20, rp: 20, unit: "box" },
  { name: "Moong Dhuli Dal Yellow Split", cat: "Kirana", wp: 98, rp: 98, unit: "kg" },
  { name: "Fair & Handsome Cream 30gm 90rs", cat: "Household", wp: 85, rp: 85, unit: "pc" },
  { name: "Crax Krunch Namkeen 5rs", cat: "Snacks", wp: 54, rp: 54, unit: "pc" },
  { name: "Mota Magaj Watermelon Seeds", cat: "Kirana", wp: 640, rp: 680, unit: "kg" },
  { name: "Haldi Powder 50g 20rs", cat: "Masala", wp: 18, rp: 18, unit: "pc" },
  { name: "Cadbury Gems 5rs", cat: "Snacks", wp: 240, rp: 240, unit: "box" },
  { name: "Whisper Sanitary Pads 50rs", cat: "Household", wp: 44, rp: 44, unit: "pc" },
  { name: "Pampers Baby Diapers 20rs", cat: "Household", wp: 130, rp: 130, unit: "pc" },
  { name: "Orion Choco Pie 10rs", cat: "Snacks", wp: 125, rp: 125, unit: "box" },
  { name: "Dove Deep Moisture Soap 62rs", cat: "Household", wp: 57, rp: 57, unit: "pc" },
  { name: "Tata Tea Premium 100g", cat: "Kirana", wp: 136, rp: 136, unit: "pc" },
  { name: "Non Stop Energy Drink Can", cat: "Drinks", wp: 950, rp: 950, unit: "box" },
  { name: "Madhav Tibar Basmati Rice", cat: "Rice & Atta", wp: 1220, rp: 1220, unit: "kg" },
  { name: "Corn Flour Ararot Powder", cat: "Kirana", wp: 40, rp: 40, unit: "kg" },
  { name: "TGF Tea 250gm", cat: "Kirana", wp: 80, rp: 80, unit: "pc" },
  { name: "Jeera Cumin Seeds 100g", cat: "Masala", wp: 32, rp: 32, unit: "pc" },
  { name: "Sunsilk Shampoo 1rs Sachet", cat: "Household", wp: 13, rp: 15, unit: "box" },
  { name: "Padlock Tala 62mm", cat: "Household", wp: 240, rp: 240, unit: "pc" },
  { name: "Patanjali Rock Salt Namak 1kg", cat: "Kirana", wp: 350, rp: 350, unit: "box" },
  { name: "Parle Kismi Toffee 50rs Pouch", cat: "Snacks", wp: 40, rp: 40, unit: "pkt" },
  { name: "Impact Detergent Powder 5kg", cat: "Household", wp: 520, rp: 520, unit: "kg" },
  { name: "Safed Matar White Peas", cat: "Kirana", wp: 70, rp: 75, unit: "kg" },
  { name: "Boroplus Antiseptic Cream 19ml 45rs", cat: "Household", wp: 41, rp: 41, unit: "pc" },
  { name: "Tomato Sauce 5L Commercial Can", cat: "Kirana", wp: 250, rp: 250, unit: "can" },
  { name: "Parachute Coconut Hair Oil 200ml 131rs", cat: "Household", wp: 115, rp: 115, unit: "pc" },
  { name: "Clinic Plus Shampoo 1rs Sachet", cat: "Household", wp: 13, rp: 13, unit: "box" },
  { name: "Chakarpani Basmati Rice 26kg", cat: "Rice & Atta", wp: 38.08, rp: 38.08, unit: "kg" },
  { name: "MDH Shahi Paneer Masala 100g", cat: "Masala", wp: 80, rp: 80, unit: "pc" },
  { name: "All Out Mosquito Machine Set 105rs", cat: "Household", wp: 95, rp: 95, unit: "set" },
  { name: "Panchratan Dal Mixture 100rs", cat: "Snacks", wp: 90, rp: 90, unit: "pc" },
  { name: "Iodex Fast Relief Balm 88rs", cat: "Household", wp: 80, rp: 80, unit: "pc" },
  { name: "Corn Flakes Mixture Namkeen 5rs", cat: "Snacks", wp: 52, rp: 52, unit: "pc" },
  { name: "Local Packaged Drinking Water 1L", cat: "Drinks", wp: 7.5, rp: 7.5, unit: "pc" },
  { name: "Party Red Basmati Rice 26kg", cat: "Rice & Atta", wp: 1450, rp: 1450, unit: "kg" },
  { name: "Black Magic Biscuits 5rs", cat: "Snacks", wp: 50.83, rp: 54, unit: "pc" },
  { name: "Parle Kismi Chocolate 2rs", cat: "Snacks", wp: 100, rp: 100, unit: "box" },
  { name: "Imli Tamarind 1kg Slab", cat: "Masala", wp: 62, rp: 62, unit: "kg" },
  { name: "Dettol Handwash Pump 200ml 99rs", cat: "Household", wp: 90, rp: 90, unit: "pc" },
  { name: "Navratna Cool Talc Powder 10rs", cat: "Household", wp: 100, rp: 100, unit: "box" },
  { name: "Sabudana Sago Loose", cat: "Kirana", wp: 75, rp: 75, unit: "kg" },
  { name: "Khand Raw Sugar 1kg", cat: "Kirana", wp: 68, rp: 70, unit: "kg" },
  { name: "Kabuli Chana Chole Medium", cat: "Kirana", wp: 85, rp: 90, unit: "kg" },
  { name: "Tej Patta Bay Leaves Whole", cat: "Masala", wp: 200, rp: 200, unit: "kg" },
  { name: "Nip Dishwash Bar 10rs", cat: "Household", wp: 8.58, rp: 8.58, unit: "pc" },
  { name: "Gas Lighter 20rs", cat: "Household", wp: 600, rp: 600, unit: "box" },
  { name: "Hit Mosquito Spray Red 99rs", cat: "Household", wp: 90, rp: 90, unit: "pc" },
  { name: "Rajnigandha Pan Masala", cat: "Tobacco", wp: 18.7, rp: 18.7, unit: "pc" },
  { name: "Kismis Indian Raisins Loose", cat: "Kirana", wp: 440, rp: 450, unit: "kg" },
  { name: "Ocean Special Chai Tea 10rs", cat: "Kirana", wp: 120, rp: 120, unit: "box" },
  { name: "Red Chilli Mirch Powder 100g", cat: "Masala", wp: 34, rp: 40, unit: "pc" },
  { name: "Ponds Moisturising Body Lotion 275ml", cat: "Household", wp: 380, rp: 380, unit: "pc" },
  { name: "Margo Neem Soap Set 105rs", cat: "Household", wp: 90, rp: 90, unit: "set" },
  { name: "Four-1 Refined Oil 500ml", cat: "Kirana", wp: 80.67, rp: 81, unit: "pc" },
  { name: "Nippon LED Emergency Bulb", cat: "Household", wp: 38, rp: 38, unit: "pc" },
  { name: "Dilbagh Pan Masala", cat: "Tobacco", wp: 130, rp: 130, unit: "box" },
  { name: "Meethi Kheel Sugar Puffed Loose", cat: "Kirana", wp: 78, rp: 80, unit: "kg" },
  { name: "Patanjali Cow Ghee 500gm 393rs", cat: "Kirana", wp: 340, rp: 340, unit: "pc" },
  { name: "Fortune Soyabean Refined Oil 1L", cat: "Kirana", wp: 188.5, rp: 190, unit: "l" },
  { name: "Funtop Soya Sauce 1L Bottle", cat: "Kirana", wp: 70, rp: 70, unit: "pc" },
  { name: "Sarvodaya Chakki Atta 10kg", cat: "Rice & Atta", wp: 320, rp: 320, unit: "kg" },
  { name: "Meethi Kheel Sugar Puffed 500g Pkt", cat: "Kirana", wp: 70, rp: 70, unit: "pc" },
  { name: "Fiama Gel Soap Bar Set 372rs", cat: "Household", wp: 300, rp: 300, unit: "set" },
  { name: "Real Mixed Fruit Juice 1L", cat: "Drinks", wp: 1180, rp: 1180, unit: "box" },
  { name: "Mortein Mosquito Coil", cat: "Household", wp: 26, rp: 26, unit: "box" },
  { name: "Nescafe Classic Coffee Jar 90gm", cat: "Kirana", wp: 405, rp: 405, unit: "pc" },
  { name: "Appy Fizz Sparkling Apple Drink 20rs", cat: "Drinks", wp: 17.33, rp: 17.33, unit: "pc" },
  { name: "Nimbooz Lemon Drink 250ml", cat: "Drinks", wp: 520, rp: 520, unit: "box" },
  { name: "Navratna Ayurvedic Hair Oil 1rs", cat: "Household", wp: 340, rp: 390, unit: "box" },
  { name: "MDH Kashmiri Mirch 100g", cat: "Masala", wp: 100, rp: 100, unit: "pc" },
  { name: "Mango Pickle Achar 500gm", cat: "Kirana", wp: 68, rp: 68, unit: "pc" },
  { name: "Boroplus Antiseptic Cream 5rs", cat: "Household", wp: 82, rp: 82, unit: "box" },
  { name: "Dainik Lal Basmati Rice 26kg", cat: "Rice & Atta", wp: 49.23, rp: 49.23, unit: "kg" },
  { name: "Methi Laungi Fenugreek Cloves Mix", cat: "Masala", wp: 195, rp: 195, unit: "kg" },
  { name: "Pampers Baby Diapers 35rs", cat: "Household", wp: 31.25, rp: 31.25, unit: "pc" },
  { name: "Ghadi Washing Soap 5rs", cat: "Household", wp: 4.5, rp: 4.5, unit: "pc" },
  { name: "Lays Classic Salted 5rs", cat: "Snacks", wp: 54, rp: 56, unit: "pc" },
  { name: "Jasmine Hair Oil 20rs Bottle", cat: "Household", wp: 18, rp: 19, unit: "pc" },
  { name: "Choti Advance Cigarette", cat: "Tobacco", wp: 110, rp: 110, unit: "box" },
  { name: "Moong Chilka Dal Split Green", cat: "Kirana", wp: 98, rp: 98, unit: "kg" },
  { name: "Kaju Mix Namkeen 10rs", cat: "Snacks", wp: 100, rp: 100, unit: "pc" },
  { name: "All in One Mixture 10rs", cat: "Snacks", wp: 100, rp: 100, unit: "pc" },
  { name: "Mix Dry Fruits Assorted 500g", cat: "Kirana", wp: 260, rp: 280, unit: "pc" },
  { name: "Coconut Candy Toffee Jar 170 Pcs", cat: "Snacks", wp: 140, rp: 140, unit: "jar" },
  { name: "Smoothies Fruit Candy Jar", cat: "Snacks", wp: 130, rp: 130, unit: "jar" },
  { name: "Blue Gel Pen Nataraj", cat: "Stationery", wp: 20, rp: 20, unit: "box" },
  { name: "Bura Sugar 1kg Pkt", cat: "Kirana", wp: 68, rp: 68, unit: "pc" },
  { name: "Fortune Refined Oil Tin 15L", cat: "Kirana", wp: 2300, rp: 2300, unit: "tin" },
  { name: "Aam Ka Achar Mango Pickle 1kg", cat: "Kirana", wp: 130, rp: 130, unit: "kg" },
  { name: "Akhrot Sabut Whole Walnuts in Shell", cat: "Kirana", wp: 600, rp: 600, unit: "kg" },
  { name: "Mishri Crystal Sugar Lump", cat: "Masala", wp: 80, rp: 80, unit: "kg" },
  { name: "Funtoosh Candy Jar", cat: "Snacks", wp: 130, rp: 130, unit: "jar" },
  { name: "Zandu Balm Fast Pain Relief 46rs", cat: "Household", wp: 40, rp: 40, unit: "pc" },
  { name: "Parle Marigold Biscuits 10rs", cat: "Snacks", wp: 9, rp: 10, unit: "pc" },
  { name: "Lifebuoy Soap 4-Pack Set 155rs", cat: "Household", wp: 140, rp: 145, unit: "set" },
  { name: "Himalaya Purifying Neem Face Wash 50ml", cat: "Household", wp: 80, rp: 80, unit: "pc" },
  { name: "Tide Plus Detergent Powder 7kg", cat: "Household", wp: 640, rp: 640, unit: "kg" },
  { name: "Vaseline Petroleum Jelly 10rs", cat: "Household", wp: 210, rp: 210, unit: "box" },
  { name: "Colgate Dental Cream 10rs", cat: "Household", wp: 105, rp: 105, unit: "box" },
  { name: "Maaza Mango Drink 1L Bottle", cat: "Drinks", wp: 58.33, rp: 58.33, unit: "pc" },
  { name: "Denver Deodorant Body Spray 150ml", cat: "Household", wp: 180, rp: 200, unit: "pc" },
  { name: "Cavanders Cigarette", cat: "Tobacco", wp: 90, rp: 90, unit: "box" },
  { name: "Gathiya Namkeen 10rs", cat: "Snacks", wp: 100, rp: 100, unit: "pc" },
  { name: "Ponds Sandal Talc Powder 10rs", cat: "Household", wp: 9.09, rp: 9.09, unit: "pc" },
];

function generateCleanSku(name: string, index: number, seen: Set<string>): string {
  let cleaned = name
    .toUpperCase()
    .replace(/[^\w\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-");

  if (!cleaned || cleaned.length < 3) cleaned = `PROD-${index + 1}`;
  let candidate = cleaned;
  let counter = 2;
  while (seen.has(candidate)) {
    candidate = `${cleaned}-${counter}`;
    counter++;
  }
  seen.add(candidate);
  return candidate;
}

async function run() {
  console.log("Connecting to database and ensuring standard units...");
  const unitDefs = [
    { name: "kilogram", symbol: "kg", type: "WEIGHT" as const },
    { name: "gram", symbol: "g", type: "WEIGHT" as const },
    { name: "litre", symbol: "l", type: "VOLUME" as const },
    { name: "millilitre", symbol: "ml", type: "VOLUME" as const },
    { name: "piece", symbol: "pc", type: "COUNT" as const },
    { name: "box", symbol: "box", type: "COUNT" as const },
    { name: "dozen", symbol: "dz", type: "COUNT" as const },
    { name: "packet", symbol: "pkt", type: "COUNT" as const },
    { name: "can", symbol: "can", type: "COUNT" as const },
    { name: "jar", symbol: "jar", type: "COUNT" as const },
    { name: "set", symbol: "set", type: "COUNT" as const },
    { name: "tin", symbol: "tin", type: "COUNT" as const },
  ];

  const dbUnits = await Promise.all(
    unitDefs.map((u) => db.unit.upsert({ where: { symbol: u.symbol }, update: {}, create: u }))
  );
  const unitMap = Object.fromEntries(dbUnits.map((u) => [u.symbol, u.id]));

  console.log(`Units verified. Total products to import: ${rawData.length}`);
  const seenSkus = new Set<string>();

  let inserted = 0;
  for (let i = 0; i < rawData.length; i++) {
    const item = rawData[i];
    if (!item) continue;
    const sku = generateCleanSku(item.name, i, seenSkus);
    const unitId = unitMap[item.unit] || unitMap.pc || dbUnits[0]?.id || "";

    await db.product.upsert({
      where: { sku },
      update: {
        name: item.name,
        category: item.cat,
        wholesalePrice: item.wp,
        retailPrice: item.rp,
        baseUnitId: unitId,
        active: true,
      },
      create: {
        sku,
        name: item.name,
        category: item.cat,
        wholesalePrice: item.wp,
        retailPrice: item.rp,
        baseUnitId: unitId,
        active: true,
      },
    });

    inserted++;
    if (inserted % 30 === 0 || inserted === rawData.length) {
      console.log(`Imported ${inserted}/${rawData.length} products...`);
    }
  }

  console.log("✅ All products successfully added to database!");
  const totalInDb = await db.product.count();
  console.log(`Total active products in database: ${totalInDb}`);
  process.exit(0);
}

run().catch((err) => {
  console.error("Error running product import:", err);
  process.exit(1);
});
